//! Replays `fixtures/reference/blocks.json.gz`, generated by `tools/refgen/run.sh` from the real
//! upstream MovementHelper / PrecomputedData / BetterWorldBorder running against the real
//! Minecraft client.
//!
//! The fixture holds the Java-semantics block state table (every 26.3 state, as a host would
//! send it), the upstream results of the per-state checks for every state, and the upstream
//! results of the position checks in random small worlds, each under two settings: upstream
//! defaults (`a`) and every setting read by these checks changed (`b`).

use std::collections::BTreeMap;
use std::fmt::Write;
use std::io::Read;
use std::sync::{Arc, LazyLock, Mutex, MutexGuard};

use baritone::api::utils::BetterBlockPos;
use baritone::host::{
    BlockState, BlockStateTable, Chunk, DimensionType, OffsetType, World, WorldBorder,
};
use baritone::mc::Aabb;
use baritone::pathing::movement::movement_helper as mh;
use baritone::pathing::precompute::{PrecomputedData, Ternary};
use baritone::settings::{Settings, set_settings};
use baritone::utils::BlockStateInterface;
use flate2::read::GzDecoder;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    upstream: String,
    minecraft: String,
    table: BlockStateTable,
    offsets: Vec<OffsetSample>,
    configs: BTreeMap<String, Settings>,
    state_refs: BTreeMap<String, Vec<String>>,
    worlds: Vec<FixtureWorld>,
}

/// A state with an offset at a position: `getOffset(pos)` and the moved shapes (`toAabbs()`),
/// as raw double bits.
#[derive(Deserialize)]
struct OffsetSample {
    state: u32,
    pos: [i32; 3],
    offset: [i64; 3],
    outline: Vec<i64>,
    collision: Vec<i64>,
}

#[derive(Deserialize)]
struct FixtureWorld {
    min_y: i32,
    height: i32,
    origin: [i32; 3],
    size: [i32; 3],
    /// State ids, x outermost, then y, then z.
    blocks: Vec<u32>,
    unloaded_chunks: Vec<[i32; 2]>,
    /// min x, max x, min z, max z
    border: [f64; 4],
    /// Per config: `POSITION_CHECKS.len()` characters per position, for x from `origin.x - 1`
    /// to `origin.x + size.x` inclusive (outermost), then y, then z.
    results: BTreeMap<String, String>,
}

static FIXTURE: LazyLock<Fixture> = LazyLock::new(|| {
    let mut json = String::new();
    GzDecoder::new(&include_bytes!("fixtures/reference/blocks.json.gz")[..])
        .read_to_string(&mut json)
        .unwrap();
    serde_json::from_str(&json).unwrap()
});

static TABLE: LazyLock<Arc<BlockStateTable>> = LazyLock::new(|| Arc::new(FIXTURE.table.clone()));

/// Settings are process-global; tests that set them take this lock.
static SETTINGS_LOCK: Mutex<()> = Mutex::new(());

fn with_config(config: &str) -> MutexGuard<'static, ()> {
    let guard = SETTINGS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    set_settings(FIXTURE.configs[config].clone());
    guard
}

fn t(v: Ternary) -> char {
    match v {
        Ternary::Yes => 'Y',
        Ternary::Maybe => 'M',
        Ternary::No => 'N',
    }
}

fn b(v: bool) -> char {
    if v { '1' } else { '0' }
}

/// Keep in sync with `stateRef` in tools/refgen/src/refgen/BlockRefGen.java.
#[allow(clippy::type_complexity)]
const STATE_CHECKS: &[(&str, fn(&BlockState) -> char)] = &[
    ("canWalkOnBlockState", |s| t(mh::can_walk_on_block_state(s))),
    ("canWalkThroughBlockState", |s| {
        t(mh::can_walk_through_block_state(s))
    }),
    ("fullyPassableBlockState", |s| {
        t(mh::fully_passable_block_state(s))
    }),
    ("isBlockNormalCube", |s| b(mh::is_block_normal_cube(s))),
    ("isWater", |s| b(mh::is_water(s))),
    ("isLava", |s| b(mh::is_lava(s))),
    ("isLiquid", |s| b(mh::is_liquid(s))),
    ("possiblyFlowing", |s| b(mh::possibly_flowing(s))),
    ("isClimbable", |s| b(mh::is_climbable(s))),
    ("avoidWalkingInto", |s| b(mh::avoid_walking_into(s))),
    ("isBottomSlab", |s| b(mh::is_bottom_slab(s))),
    ("isTransparent", |s| b(mh::is_transparent(s))),
    ("FallingBlock.isFree", |s| b(mh::falling_block_is_free(s))),
];

/// Keep in sync with `positionRef` in tools/refgen/src/refgen/BlockRefGen.java.
const POSITION_CHECKS: &[&str] = &[
    "PrecomputedData.canWalkOn",
    "PrecomputedData.canWalkThrough",
    "PrecomputedData.fullyPassable",
    "canWalkOn(bsi)",
    "canWalkThrough(bsi)",
    "isFlowing",
    "isReplaceable",
    "avoidBreaking",
    "canPlaceAgainst",
];

fn position_ref(
    bsi: &BlockStateInterface,
    pd: &PrecomputedData,
    x: i32,
    y: i32,
    z: i32,
) -> [char; 9] {
    let s = bsi.get0(x, y, z);
    [
        b(pd.can_walk_on(bsi, x, y, z, s)),
        b(pd.can_walk_through(bsi, x, y, z, s)),
        b(pd.fully_passable(bsi, x, y, z, s)),
        b(mh::can_walk_on_bsi(bsi, x, y, z)),
        b(mh::can_walk_through_bsi(bsi, x, y, z)),
        b(mh::is_flowing(x, y, z, s, bsi)),
        b(mh::is_replaceable(x, y, z, s, bsi)),
        b(mh::avoid_breaking(bsi, x, y, z, s)),
        b(mh::can_place_against(bsi, x, y, z)),
    ]
}

fn describe(state: &BlockState) -> String {
    let mut s = format!("#{} {}", state.id, state.name);
    if !state.properties.is_empty() {
        let props: Vec<_> = state
            .properties
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect();
        write!(s, "[{}]", props.join(",")).unwrap();
    }
    s
}

#[track_caller]
fn assert_no_mismatches(mismatches: &[String], total: usize) {
    if !mismatches.is_empty() {
        let shown: Vec<_> = mismatches.iter().take(30).map(String::as_str).collect();
        panic!(
            "{} of {total} checks differ from upstream, first {}:\n{}",
            mismatches.len(),
            shown.len(),
            shown.join("\n")
        );
    }
}

#[test]
fn fixture_is_for_pinned_upstream() {
    let upstream = include_str!("../UPSTREAM").trim();
    assert_eq!(
        FIXTURE.upstream, upstream,
        "regenerate with tools/refgen/run.sh"
    );
    assert_eq!(FIXTURE.minecraft, "26.3");
}

#[test]
fn java_table() {
    let table = &*TABLE;
    assert_eq!(table.len(), FIXTURE.state_refs["a"].len());
    assert_eq!(table.air().name, "minecraft:air");
    let air: Vec<_> = table
        .iter()
        .filter(|s| s.air)
        .map(|s| s.name.as_str())
        .collect();
    assert_eq!(
        air,
        ["minecraft:air", "minecraft:void_air", "minecraft:cave_air"]
    );
    for (i, state) in table.iter().enumerate() {
        assert_eq!(state.id as usize, i);
    }
}

#[test]
fn offsets_and_moved_shapes_match_upstream() {
    let bits = |boxes: &mut dyn Iterator<Item = Aabb>| -> Vec<i64> {
        boxes
            .flat_map(<[f64; 6]>::from)
            .map(|d| d.to_bits() as i64)
            .collect()
    };
    let mut mismatches = Vec::new();
    let mut offset_states = std::collections::BTreeSet::new();
    for sample in &FIXTURE.offsets {
        let state = TABLE.get(sample.state);
        let pos = BetterBlockPos::new(sample.pos[0], sample.pos[1], sample.pos[2]);
        offset_states.insert(state.name.as_str());
        let offset = state.get_offset(pos);
        let got = [offset.x, offset.y, offset.z].map(|d| d.to_bits() as i64);
        if got != sample.offset {
            mismatches.push(format!("getOffset({pos}) of {}", describe(state)));
        }
        if bits(&mut state.get_shape(pos).to_aabbs()) != sample.outline {
            mismatches.push(format!("getShape({pos}) of {}", describe(state)));
        }
        if bits(&mut state.get_collision_shape(pos).to_aabbs()) != sample.collision {
            mismatches.push(format!("getCollisionShape({pos}) of {}", describe(state)));
        }
    }
    assert_no_mismatches(&mismatches, FIXTURE.offsets.len() * 3);
    // flowers (XZ), bamboo and pointed dripstone (smaller offsets, collision moves too), an
    // XYZ block, and one that is only drawn offset
    for name in [
        "minecraft:poppy",
        "minecraft:bamboo",
        "minecraft:pointed_dripstone",
        "minecraft:small_dripleaf",
        "minecraft:short_grass",
    ] {
        assert!(offset_states.contains(name), "{name} has no offset");
    }
    let offset_of = |name: &str| {
        TABLE
            .iter()
            .find(|s| s.name == name)
            .and_then(|s| s.offset)
            .unwrap()
    };
    assert_eq!(
        offset_of("minecraft:small_dripleaf").offset_type,
        OffsetType::Xyz
    );
    assert!(offset_of("minecraft:poppy").outline && !offset_of("minecraft:poppy").collision);
    assert!(offset_of("minecraft:bamboo").collision);
    assert!(!offset_of("minecraft:short_grass").outline);
    // interaction shapes: hopper, cauldron, composter, scaffolding
    let with_interaction: std::collections::BTreeSet<_> = TABLE
        .iter()
        .filter(|s| !s.interaction_shape.is_empty())
        .map(|s| s.name.as_str())
        .collect();
    assert_eq!(
        with_interaction,
        [
            "minecraft:cauldron",
            "minecraft:composter",
            "minecraft:hopper",
            "minecraft:lava_cauldron",
            "minecraft:powder_snow_cauldron",
            "minecraft:scaffolding",
            "minecraft:water_cauldron",
        ]
        .into()
    );
}

#[test]
fn state_checks_match_upstream() {
    let mut mismatches = Vec::new();
    let mut total = 0;
    for (config, refs) in &FIXTURE.state_refs {
        let _settings = with_config(config);
        for (state, expected) in TABLE.iter().zip(refs) {
            let expected: Vec<char> = expected.chars().collect();
            assert_eq!(expected.len(), STATE_CHECKS.len(), "fixture layout");
            for ((name, check), &want) in STATE_CHECKS.iter().zip(&expected) {
                total += 1;
                let got = check(state);
                if got != want {
                    mismatches.push(format!(
                        "config {config}: {name}({}) = {got}, upstream {want}",
                        describe(state)
                    ));
                }
            }
        }
    }
    assert_no_mismatches(&mismatches, total);
}

fn build_world(w: &FixtureWorld) -> Arc<World> {
    let dimension = DimensionType {
        min_y: w.min_y,
        height: w.height,
        water_evaporates: false,
    };
    let mut world = World::new(Arc::clone(&TABLE), dimension).unwrap();
    world.set_border(WorldBorder {
        min_x: w.border[0],
        max_x: w.border[1],
        min_z: w.border[2],
        max_z: w.border[3],
    });
    let [x0, y0, z0] = w.origin;
    let [sx, sy, sz] = w.size;
    // every chunk a check may read (positions around the region, and their neighbours)
    for cx in (x0 - 2) >> 4..=(x0 + sx + 1) >> 4 {
        for cz in (z0 - 2) >> 4..=(z0 + sz + 1) >> 4 {
            if !w.unloaded_chunks.contains(&[cx, cz]) {
                world
                    .load_chunk(cx, cz, Chunk::new(dimension.section_count()))
                    .unwrap();
            }
        }
    }
    let mut ids = w.blocks.iter();
    for x in x0..x0 + sx {
        for y in y0..y0 + sy {
            for z in z0..z0 + sz {
                world.set_block(x, y, z, *ids.next().unwrap()).unwrap();
            }
        }
    }
    assert!(ids.next().is_none());
    Arc::new(world)
}

#[test]
fn position_checks_match_upstream() {
    let mut mismatches = Vec::new();
    let mut total = 0;
    // each check must see both answers somewhere, or the fixture tests nothing
    let mut seen = [[false; 2]; POSITION_CHECKS.len()];
    for (index, w) in FIXTURE.worlds.iter().enumerate() {
        let world = build_world(w);
        let [x0, y0, z0] = w.origin;
        let [sx, sy, sz] = w.size;
        for (config, results) in &w.results {
            let _settings = with_config(config);
            let bsi = BlockStateInterface::new(Arc::clone(&world));
            let pd = PrecomputedData::new(bsi.table());
            let mut expected = results.chars();
            for x in x0 - 1..=x0 + sx {
                for y in y0 - 1..=y0 + sy {
                    for z in z0 - 1..=z0 + sz {
                        let got = position_ref(&bsi, &pd, x, y, z);
                        for (i, &got) in got.iter().enumerate() {
                            total += 1;
                            let want = expected.next().expect("fixture layout");
                            seen[i][(want == '1') as usize] = true;
                            if got != want {
                                mismatches.push(format!(
                                    "world {index}, config {config}: {}({x}, {y}, {z}) on {} = {got}, upstream {want}",
                                    POSITION_CHECKS[i],
                                    describe(bsi.get0(x, y, z))
                                ));
                            }
                        }
                    }
                }
            }
            assert!(expected.next().is_none(), "fixture layout");
        }
    }
    assert_no_mismatches(&mismatches, total);
    for (name, seen) in POSITION_CHECKS.iter().zip(seen) {
        assert_eq!(
            seen,
            [true, true],
            "{name} is always the same in the fixture"
        );
    }
}
