//! Replays `fixtures/reference/exec.json.gz`, generated by `tools/refgen/run.sh`: the real
//! upstream execution code (PathingBehavior, PathExecutor, the movements' updateState,
//! LookBehavior, InventoryBehavior, InputOverrideHandler and its break and place helpers,
//! PathingControlManager, the processes) run tick by tick around a simulated client
//! (`ExecRefGen.java`), which `common::sim` mirrors around the port.
//!
//! Every tick of every scenario is compared: the player's position, motion and rotation (bit
//! for bit), crouching, sprinting, the selected slot, the inputs Baritone forces, whether it
//! drives the movement input, the game mode calls (breaking, placing, inventory swaps, arm
//! swings), the path events, the current path's position and length, the pathing command
//! (type and goal) and the process in control. `REPLAY_TRACE=<scenario name>` prints every
//! tick of that scenario, both sides.
//!
//! The fixture also holds samples of the geometry execution relies on: raytraces
//! (`RayTraceUtils.rayTraceTowards`, i.e. `Level.clip` with outline shapes), block centers
//! (`VecUtils.calculateBlockCenter`), and `RotationUtils.reachable` with the look behavior's
//! aim processor, `playerFeet` and `pathStart`, in a world of assorted shapes.

mod common;

use std::io::Read;
use std::sync::{Arc, LazyLock, Mutex, MutexGuard};

use baritone::api::event::events::PathEvent;
use baritone::api::event::events::tick_event;
use baritone::api::pathing::goals::GoalBlock;
use baritone::api::utils::input::Input;
use baritone::api::utils::{
    BetterBlockPos, BlockOptionalMeta, IPlayerContext, Rotation, ray_trace_utils, rotation_utils,
    vec_utils,
};
use baritone::behavior::PathingBehavior;
use baritone::host::{Chunk, DimensionType, Entity, Inventory, ItemStack, Player, World};
use baritone::mc::{HitResultType, Vec3};
use baritone::process::{FarmProcess, GetToBlockProcess, MineProcess};
use baritone::settings::{Settings, set_settings};
use common::TABLE;
use common::sim::{Sim, TickRecord};
use flate2::read::GzDecoder;
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct Fixture {
    upstream: String,
    minecraft: String,
    scenarios: Vec<Scenario>,
    geometry: Geometry,
}

#[derive(Deserialize)]
struct FixtureWorld {
    x0: i32,
    z0: i32,
    sx: i32,
    sz: i32,
    min_y: i32,
    height: i32,
    nether: bool,
    /// [id, count, ...]; x outermost, then z, then y
    blocks: Vec<u32>,
    loaded_chunks: Vec<[i32; 2]>,
}

#[derive(Deserialize)]
struct Scenario {
    name: String,
    world: FixtureWorld,
    /// double bits
    start: [i64; 3],
    /// The custom goal process's goal, without `process`.
    goal: Option<[i32; 3]>,
    /// Which process starts how (`ExecRefGen.start`).
    process: Option<Value>,
    inventory: Inventory,
    config: Value,
    seed: i64,
    entities: Vec<Entity>,
    /// Chunks within this radius of the player load after every tick.
    load_radius: Option<i32>,
    /// Applied after their tick.
    events: Vec<Event>,
    ticks: Vec<ExpectedTick>,
}

#[derive(Deserialize)]
struct Event {
    tick: usize,
    /// double bits
    teleport: Option<[i64; 3]>,
    /// The other entities from now on.
    entities: Option<Vec<Entity>>,
    /// A box of blocks set to `state`.
    from: Option<[i32; 3]>,
    to: Option<[i32; 3]>,
    state: Option<u32>,
}

impl Event {
    fn apply(&self, sim: &mut Sim) {
        if let Some(teleport) = self.teleport {
            sim.teleport(vec3(teleport));
            return;
        }
        if let Some(entities) = &self.entities {
            sim.set_entities(entities.clone());
            return;
        }
        let (a, b, state) = (self.from.unwrap(), self.to.unwrap(), self.state.unwrap());
        for x in a[0].min(b[0])..=a[0].max(b[0]) {
            for y in a[1].min(b[1])..=a[1].max(b[1]) {
                for z in a[2].min(b[2])..=a[2].max(b[2]) {
                    sim.edit(BetterBlockPos::new(x, y, z), state);
                }
            }
        }
    }
}

#[derive(Deserialize)]
struct ExpectedTick {
    position: [i64; 3],
    delta_movement: [i64; 3],
    rotation: [i32; 2],
    on_ground: bool,
    crouching: bool,
    sprinting: bool,
    selected: i32,
    inputs: Vec<(String, bool)>,
    baritone_input: bool,
    actions: Vec<String>,
    events: Vec<String>,
    path: Option<(i32, usize)>,
    movement: Option<String>,
    command: Option<String>,
    in_control: Option<String>,
}

#[derive(Deserialize)]
struct Geometry {
    world: FixtureWorld,
    clips: Vec<Clip>,
    block_centers: Vec<[i64; 3]>,
    reachable: Vec<Reach>,
}

#[derive(Deserialize)]
struct Clip {
    position: [i64; 3],
    old: [i64; 3],
    eye_height: i32,
    yaw: i32,
    pitch: i32,
    reach: i64,
    sneak: bool,
    hit: Hit,
}

#[derive(Deserialize, Debug, PartialEq)]
struct Hit {
    miss: bool,
    pos: [i32; 3],
    direction: String,
    location: [i64; 3],
    inside: bool,
}

#[derive(Deserialize)]
struct Reach {
    position: [i64; 3],
    old: [i64; 3],
    on_ground: bool,
    yaw: i32,
    pitch: i32,
    target: [i32; 3],
    sneak: bool,
    distance: i64,
    reachable: Option<[i32; 2]>,
    feet: [i32; 3],
    path_start: [i32; 3],
}

static FIXTURE: LazyLock<Fixture> = LazyLock::new(|| {
    let mut json = String::new();
    GzDecoder::new(&include_bytes!("fixtures/reference/exec.json.gz")[..])
        .read_to_string(&mut json)
        .unwrap();
    serde_json::from_str(&json).unwrap()
});

/// Settings are process-global; tests that set them take this lock.
static SETTINGS_LOCK: Mutex<()> = Mutex::new(());

fn with_settings(settings: Settings) -> MutexGuard<'static, ()> {
    let guard = SETTINGS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    set_settings(settings);
    guard
}

fn dbl(bits: i64) -> f64 {
    f64::from_bits(bits as u64)
}

fn vec3(bits: [i64; 3]) -> Vec3 {
    Vec3::new(dbl(bits[0]), dbl(bits[1]), dbl(bits[2]))
}

fn pos(p: [i32; 3]) -> BetterBlockPos {
    BetterBlockPos::new(p[0], p[1], p[2])
}

/// The fixture's world with its loaded chunks.
fn build_world(w: &FixtureWorld) -> World {
    build_chunks(w, w.loaded_chunks.iter().copied())
}

/// The fixture's world with every chunk of its box loaded.
fn build_all_chunks(w: &FixtureWorld) -> World {
    let chunks = (w.x0 >> 4..=(w.x0 + w.sx - 1) >> 4)
        .flat_map(|cx| (w.z0 >> 4..=(w.z0 + w.sz - 1) >> 4).map(move |cz| [cx, cz]));
    build_chunks(w, chunks)
}

fn build_chunks(w: &FixtureWorld, chunks: impl IntoIterator<Item = [i32; 2]>) -> World {
    let dimension = DimensionType {
        min_y: w.min_y,
        height: w.height,
        water_evaporates: w.nether,
    };
    let mut world = World::new(Arc::clone(&TABLE), dimension).unwrap();
    for [cx, cz] in chunks {
        world
            .load_chunk(cx, cz, Chunk::new(dimension.section_count()))
            .unwrap();
    }
    let air = TABLE.air().id;
    let mut i = 0usize;
    for pair in w.blocks.chunks(2) {
        let (id, count) = (pair[0], pair[1] as usize);
        if id != air {
            for j in i..i + count {
                let j = j as i32;
                let y = j % w.height;
                let z = (j / w.height) % w.sz;
                let x = j / w.height / w.sz;
                world
                    .set_block(w.x0 + x, w.min_y + y, w.z0 + z, id)
                    .unwrap();
            }
        }
        i += count;
    }
    assert_eq!(i, (w.sx * w.sz * w.height) as usize, "fixture layout");
    world
}

fn input(name: &str) -> Input {
    *Input::VALUES
        .iter()
        .find(|i| i.name() == name)
        .unwrap_or_else(|| panic!("unknown input {name}"))
}

fn expected(t: &ExpectedTick) -> TickRecord {
    TickRecord {
        position: t.position.map(|b| b as u64),
        delta_movement: t.delta_movement.map(|b| b as u64),
        rotation: t.rotation.map(|b| b as u32),
        on_ground: t.on_ground,
        crouching: t.crouching,
        sprinting: t.sprinting,
        selected: t.selected,
        inputs: t.inputs.iter().map(|(k, v)| (input(k), *v)).collect(),
        baritone_input: t.baritone_input,
        actions: t.actions.clone(),
        events: t
            .events
            .iter()
            .map(|name| {
                *PATH_EVENTS
                    .iter()
                    .find(|e| e.name() == name)
                    .unwrap_or_else(|| panic!("unknown path event {name}"))
            })
            .collect(),
        path: t.path,
        movement: t.movement.as_deref().map(movement_class),
        command: t.command.clone(),
        in_control: t.in_control.as_deref().map(process_class_name),
    }
}

/// The port's name for an upstream process class.
fn process_class_name(name: &str) -> &'static str {
    [
        "BackfillProcess",
        "CustomGoalProcess",
        "ExploreProcess",
        "FarmProcess",
        "FollowProcess",
        "GetToBlockProcess",
        "InventoryPauserProcess",
        "MineProcess",
    ]
    .into_iter()
    .find(|&c| c == name)
    .unwrap_or_else(|| panic!("unknown process {name}"))
}

/// The port's name for an upstream movement class.
fn movement_class(name: &str) -> &'static str {
    [
        "MovementAscend",
        "MovementDescend",
        "MovementDiagonal",
        "MovementDownward",
        "MovementFall",
        "MovementParkour",
        "MovementPillar",
        "MovementTraverse",
    ]
    .into_iter()
    .find(|&c| c == name)
    .unwrap_or_else(|| panic!("unknown movement {name}"))
}

const PATH_EVENTS: [PathEvent; 12] = [
    PathEvent::CalcStarted,
    PathEvent::CalcFinishedNowExecuting,
    PathEvent::CalcFailed,
    PathEvent::NextSegmentCalcStarted,
    PathEvent::NextSegmentCalcFinished,
    PathEvent::ContinuingOntoPlannedNext,
    PathEvent::SplicingOntoNextEarly,
    PathEvent::AtGoal,
    PathEvent::PathFinishedNextStillCalculating,
    PathEvent::NextCalcFailed,
    PathEvent::DiscardNext,
    PathEvent::Canceled,
];

/// The fields of two records that differ, readably.
fn diff(got: &TickRecord, want: &TickRecord) -> String {
    let f = |bits: [u64; 3]| bits.map(f64::from_bits);
    let mut out = Vec::new();
    if got.position != want.position {
        out.push(format!(
            "position {:?} != {:?}",
            f(got.position),
            f(want.position)
        ));
    }
    if got.delta_movement != want.delta_movement {
        out.push(format!(
            "delta {:?} != {:?}",
            f(got.delta_movement),
            f(want.delta_movement)
        ));
    }
    if got.rotation != want.rotation {
        out.push(format!(
            "rotation {:?} != {:?}",
            got.rotation.map(f32::from_bits),
            want.rotation.map(f32::from_bits)
        ));
    }
    macro_rules! field {
        ($name:ident) => {
            if got.$name != want.$name {
                out.push(format!(
                    concat!(stringify!($name), " {:?} != {:?}"),
                    got.$name, want.$name
                ));
            }
        };
    }
    field!(on_ground);
    field!(crouching);
    field!(sprinting);
    field!(selected);
    field!(inputs);
    field!(baritone_input);
    field!(actions);
    field!(events);
    field!(path);
    field!(movement);
    field!(command);
    field!(in_control);
    out.join("\n    ")
}

#[test]
fn fixture_is_for_pinned_upstream() {
    let upstream = include_str!("../UPSTREAM").trim();
    assert_eq!(
        FIXTURE.upstream, upstream,
        "regenerate with tools/refgen/run.sh"
    );
    assert_eq!(FIXTURE.minecraft, "26.3");
}

/// `ExecRefGen.start`: starts the scenario's process.
fn start(sim: &mut Sim, scenario: &Scenario) {
    let Some(process) = &scenario.process else {
        sim.baritone
            .get_custom_goal_process_mut()
            .set_goal_and_path(Some(Arc::new(GoalBlock::from_pos(pos(scenario
                .goal
                .unwrap())))));
        return;
    };
    let str_of = |key: &str| process[key].as_str().unwrap().to_owned();
    let int_of = |key: &str| process[key].as_i64().unwrap() as i32;
    let baritone = &mut sim.baritone;
    match process["type"].as_str().unwrap() {
        "mine" => {
            let blocks: Vec<&str> = process["blocks"]
                .as_array()
                .unwrap()
                .iter()
                .map(|b| b.as_str().unwrap())
                .collect();
            MineProcess::mine_by_name(baritone, int_of("quantity"), &blocks).unwrap();
        }
        "get_to_block" => {
            let block = BlockOptionalMeta::from_selector(&TABLE, &str_of("block")).unwrap();
            GetToBlockProcess::get_to_block(baritone, block);
        }
        "follow" => {
            let entity_type = str_of("entity_type");
            baritone
                .get_follow_process_mut()
                .follow(Arc::new(move |e: &Entity| e.type_id == entity_type));
        }
        "pickup" => {
            let item = str_of("item");
            baritone
                .get_follow_process_mut()
                .pickup(move |stack: &ItemStack| stack.get_item() == item);
        }
        "explore" => baritone
            .get_explore_process_mut()
            .explore(int_of("x"), int_of("z")),
        "farm" => FarmProcess::farm(baritone, int_of("range"), None),
        other => panic!("unknown process {other}"),
    }
}

#[test]
fn execution_matches_upstream() {
    let mut failures = Vec::new();
    for scenario in &FIXTURE.scenarios {
        let settings: Settings = serde_json::from_value(scenario.config.clone()).unwrap();
        let _settings = with_settings(settings);
        let player = Player {
            position: vec3(scenario.start),
            inventory: scenario.inventory.clone(),
            ..Player::default()
        };
        let mut sim = Sim::new(build_world(&scenario.world), player, scenario.seed);
        if let Some(radius) = scenario.load_radius {
            sim.load_chunks_around(build_all_chunks(&scenario.world), radius);
        }
        sim.set_entities(scenario.entities.clone());
        start(&mut sim, scenario);
        // REPLAY_TRACE=<scenario name> prints every tick of the scenario, both sides
        let trace = std::env::var("REPLAY_TRACE").is_ok_and(|name| name == scenario.name);
        for (tick, want) in scenario.ticks.iter().enumerate() {
            let got = sim.tick();
            let want = expected(want);
            if trace {
                eprintln!("{tick} got  {got:?}\n{tick} want {want:?}");
            }
            if got != want {
                failures.push(format!(
                    "{} tick {tick}:\n    {}",
                    scenario.name,
                    diff(&got, &want)
                ));
                break;
            }
            for event in scenario.events.iter().filter(|e| e.tick == tick) {
                event.apply(&mut sim);
            }
        }
    }
    set_settings(Settings::default());
    assert!(
        failures.is_empty(),
        "{} of {} scenarios differ from upstream:\n{}",
        failures.len(),
        FIXTURE.scenarios.len(),
        failures.join("\n")
    );
}

#[test]
fn raytraces_match_upstream() {
    let world = build_world(&FIXTURE.geometry.world);
    let mut mismatches = Vec::new();
    let mut kinds = [0usize; 3]; // misses, hits, starting inside
    for (i, c) in FIXTURE.geometry.clips.iter().enumerate() {
        let player = Player {
            position: vec3(c.position),
            old_position: vec3(c.old),
            eye_height: f32::from_bits(c.eye_height as u32),
            ..Player::default()
        };
        let rotation = Rotation::new(f32::from_bits(c.yaw as u32), f32::from_bits(c.pitch as u32));
        let hit = ray_trace_utils::ray_trace_towards_sneak(
            &player,
            &world,
            rotation,
            dbl(c.reach),
            c.sneak,
        );
        let got = Hit {
            miss: hit.get_type() == HitResultType::Miss,
            pos: [
                hit.get_block_pos().x,
                hit.get_block_pos().y,
                hit.get_block_pos().z,
            ],
            direction: hit.get_direction().get_name().to_owned(),
            location: {
                let l = hit.get_location();
                [l.x, l.y, l.z].map(|d| d.to_bits() as i64)
            },
            inside: hit.is_inside(),
        };
        kinds[if got.miss {
            0
        } else if got.inside {
            2
        } else {
            1
        }] += 1;
        if got != c.hit {
            mismatches.push(format!("clip {i}: {got:?} != {:?}", c.hit));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} raytraces differ:\n{}",
        mismatches.len(),
        FIXTURE.geometry.clips.len(),
        mismatches
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
    assert!(
        kinds.iter().all(|&n| n > 0),
        "misses, hits, inside: {kinds:?}"
    );
}

#[test]
fn block_centers_match_upstream() {
    let w = &FIXTURE.geometry.world;
    let world = build_world(w);
    let mut expected = FIXTURE.geometry.block_centers.iter();
    let mut mismatches = Vec::new();
    for x in -16..16 {
        for y in -12..16 {
            for z in -16..16 {
                let p = BetterBlockPos::new(x, y, z);
                let got = vec_utils::calculate_block_center(&world, p);
                let want = vec3(*expected.next().expect("fixture layout"));
                if [got.x, got.y, got.z].map(f64::to_bits)
                    != [want.x, want.y, want.z].map(f64::to_bits)
                {
                    mismatches.push(format!(
                        "{p} ({}): {got:?} != {want:?}",
                        world.get_block_state(p).name
                    ));
                }
            }
        }
    }
    assert!(expected.next().is_none(), "fixture layout");
    assert!(
        mismatches.is_empty(),
        "{} block centers differ:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn reachable_matches_upstream() {
    let _settings = with_settings(Settings::default());
    let world = build_world(&FIXTURE.geometry.world);
    let player = Player {
        position: Vec3::new(0.5, 0.0, 0.5),
        ..Player::default()
    };
    let mut sim = Sim::new(world, player, 42);
    let mut mismatches = Vec::new();
    let mut found = 0;
    for (i, r) in FIXTURE.geometry.reachable.iter().enumerate() {
        {
            let player = sim.baritone.player_mut().unwrap();
            player.position = vec3(r.position);
            player.old_position = vec3(r.old);
            player.eye_height = Player::STANDING_EYE_HEIGHT;
            player.bounding_box = Player::standing_box(player.position);
            player.on_ground = r.on_ground;
            player.y_rot = f32::from_bits(r.yaw as u32);
            player.x_rot = f32::from_bits(r.pitch as u32);
        }
        sim.baritone
            .get_look_behavior_mut()
            .on_tick(tick_event::Type::In); // advances the aim processor
        let ctx = sim.baritone.get_player_context();
        let got = rotation_utils::reachable_distance_sneak(
            ctx,
            sim.baritone.get_look_behavior().get_aim_processor(),
            pos(r.target),
            dbl(r.distance),
            r.sneak,
        )
        .map(|rot| {
            [
                rot.get_yaw().to_bits() as i32,
                rot.get_pitch().to_bits() as i32,
            ]
        });
        found += got.is_some() as usize;
        if got != r.reachable {
            mismatches.push(format!(
                "sample {i}: reachable {got:?} != {:?}",
                r.reachable
            ));
        }
        let feet = ctx.player_feet();
        if [feet.x, feet.y, feet.z] != r.feet {
            mismatches.push(format!("sample {i}: playerFeet {feet} != {:?}", r.feet));
        }
        let start = PathingBehavior::path_start(ctx);
        if [start.x, start.y, start.z] != r.path_start {
            mismatches.push(format!(
                "sample {i}: pathStart {start} != {:?}",
                r.path_start
            ));
        }
    }
    set_settings(Settings::default());
    assert!(
        mismatches.is_empty(),
        "{} checks differ:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
    assert!(found > 100, "only {found} reachable");
}
