//! Replays `fixtures/reference/paths.json.gz`, generated by `tools/refgen/run.sh` from the real
//! upstream `AStarPathFinder` (with the real `CalculationContext` methods, `MovementHelper`,
//! movements, `Path`, `ToolSet` and `Favoring`) running against the real Minecraft client's
//! blocks and items.
//!
//! The fixture holds generated worlds (terrain, block noise, flat), settings configurations and
//! inventories, and for each world: path calculations (start, goal, player, favoring, and the
//! upstream result: type, positions, movements with their costs, nodes considered) and the raw
//! result of every `Moves` at sampled positions. It also holds `ToolSet` break speeds and best
//! slots for every block. Costs are compared bit for bit. The block state table comes from
//! `fixtures/reference/blocks.json.gz`.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::io::Read;
use std::sync::{Arc, LazyLock, Mutex, MutexGuard};

use baritone::api::pathing::calc::{IPath, IPathFinder};
use baritone::api::pathing::goals::{
    Goal, GoalAxis, GoalBlock, GoalComposite, GoalGetToBlock, GoalInverted, GoalNear, GoalRunAway,
    GoalStrictDirection, GoalTwoBlocks, GoalXZ, GoalYLevel,
};
use baritone::api::pathing::movement::COST_INF;
use baritone::api::utils::BetterBlockPos;
use baritone::api::utils::path_calculation_result::Type;
use baritone::host::paletted::{self, PalettedStorage, SECTION_VOLUME};
use baritone::host::{
    BlockStateTable, Chunk, DimensionType, Inventory, MobEffectInstance, Player, SubChunk, World,
    WorldBorder,
};
use baritone::mc::Direction;
use baritone::pathing::calc::AStarPathFinder;
use baritone::pathing::movement::{CalculationContext, Movement, Moves};
use baritone::settings::{Settings, set_settings};
use baritone::utils::ToolSet;
use baritone::utils::pathing::{Avoidance, Favoring, MutableMoveResult};
use flate2::read::GzDecoder;
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct Fixture {
    upstream: String,
    minecraft: String,
    min_y: i32,
    height: i32,
    chunk_range: [i32; 2],
    timeout: i64,
    configs: BTreeMap<String, Value>,
    inventories: BTreeMap<String, Inventory>,
    tool_set: Vec<ToolSetCase>,
    worlds: Vec<FixtureWorld>,
}

#[derive(Deserialize, Debug)]
struct PlayerSpec {
    inventory: String,
    food: i32,
    frost_walker: i32,
    /// float bits
    water_efficiency: Option<u32>,
    effects: Vec<(String, i32)>,
    throwaway: bool,
}

#[derive(Deserialize)]
struct ToolSetCase {
    config: String,
    player: PlayerSpec,
    /// default state id, getStrVsBlock bits, getBestSlot(b, false), getBestSlot(b, true)
    values: Vec<(u32, i64, i32, i32)>,
}

#[derive(Deserialize)]
struct FixtureWorld {
    kind: String,
    /// [id, count, ...]; x outermost, then z, then y
    blocks: Vec<u32>,
    loaded_chunks: Vec<[i32; 2]>,
    /// min x, max x, min z, max z
    border: [f64; 4],
    move_samples: Vec<MoveSample>,
    queries: Vec<Query>,
}

/// Move ordinal, destination x, y, z, cost bits.
type MoveResult = (usize, i32, i32, i32, i64);

#[derive(Deserialize)]
struct MoveSample {
    config: String,
    player: PlayerSpec,
    /// x, y, z, and the result of every move with a finite cost
    positions: Vec<(i32, i32, i32, Vec<MoveResult>)>,
}

#[derive(Deserialize)]
struct Query {
    config: String,
    player: PlayerSpec,
    real_start: [i32; 3],
    start: [i32; 3],
    goal: Value,
    /// Positions of the previous path, flattened.
    favoring: Option<Vec<i32>>,
    /// x, y, z, coefficient bits, radius
    avoidances: Vec<(i32, i32, i32, i64, i32)>,
    context: ContextRef,
    result: ResultRef,
}

#[derive(Deserialize)]
struct ContextRef {
    has_throwaway: bool,
    has_water_bucket: bool,
    can_sprint: bool,
    water_walk_speed: i64,
}

#[derive(Deserialize)]
struct ResultRef {
    #[serde(rename = "type")]
    type_: String,
    positions: Option<Vec<i32>>,
    /// class, cost bits, calculatedWhileLoaded
    movements: Option<Vec<(String, i64, bool)>>,
    num_nodes: Option<i32>,
}

fn gunzip(bytes: &[u8]) -> String {
    let mut json = String::new();
    GzDecoder::new(bytes).read_to_string(&mut json).unwrap();
    json
}

static FIXTURE: LazyLock<Fixture> = LazyLock::new(|| {
    serde_json::from_str(&gunzip(include_bytes!("fixtures/reference/paths.json.gz"))).unwrap()
});

static TABLE: LazyLock<Arc<BlockStateTable>> = LazyLock::new(|| {
    #[derive(Deserialize)]
    struct Blocks {
        table: BlockStateTable,
    }
    let blocks: Blocks =
        serde_json::from_str(&gunzip(include_bytes!("fixtures/reference/blocks.json.gz"))).unwrap();
    Arc::new(blocks.table)
});

/// Settings are process-global; tests that set them take this lock.
static SETTINGS_LOCK: Mutex<()> = Mutex::new(());

fn with_config(config: &str) -> MutexGuard<'static, ()> {
    let guard = SETTINGS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    set_settings(serde_json::from_value(FIXTURE.configs[config].clone()).unwrap());
    guard
}

fn dbl(bits: i64) -> f64 {
    f64::from_bits(bits as u64)
}

fn player(spec: &PlayerSpec) -> Arc<Player> {
    Arc::new(Player {
        inventory: FIXTURE.inventories[&spec.inventory].clone(),
        food_level: spec.food,
        effects: spec
            .effects
            .iter()
            .map(|(effect, amplifier)| MobEffectInstance {
                effect: effect.clone(),
                amplifier: *amplifier,
            })
            .collect(),
        frost_walker: spec.frost_walker,
        water_movement_efficiency: spec.water_efficiency.map(f32::from_bits),
    })
}

fn build_world(w: &FixtureWorld) -> Arc<World> {
    let dimension = DimensionType {
        min_y: FIXTURE.min_y,
        height: FIXTURE.height,
        water_evaporates: false,
    };
    let [cmin, cmax] = FIXTURE.chunk_range;
    let (x0, z0) = (cmin * 16, cmin * 16);
    let size = ((cmax - cmin + 1) * 16) as usize;
    let height = FIXTURE.height as usize;
    let mut blocks = Vec::with_capacity(size * size * height);
    for pair in w.blocks.chunks(2) {
        blocks.extend(std::iter::repeat_n(pair[0], pair[1] as usize));
    }
    assert_eq!(blocks.len(), size * size * height, "fixture layout");

    let mut world = World::new(Arc::clone(&TABLE), dimension).unwrap();
    world.set_border(WorldBorder {
        min_x: w.border[0],
        max_x: w.border[1],
        min_z: w.border[2],
        max_z: w.border[3],
    });
    for &[cx, cz] in &w.loaded_chunks {
        let mut chunk = Chunk::new(dimension.section_count());
        for section in 0..dimension.section_count() {
            let mut ids = [0u32; SECTION_VOLUME];
            for lx in 0..16 {
                for lz in 0..16 {
                    let x = (cx * 16 - x0) as usize + lx;
                    let z = (cz * 16 - z0) as usize + lz;
                    for ly in 0..16 {
                        let y = section * 16 + ly;
                        ids[paletted::index(lx, ly, lz)] = blocks[(x * size + z) * height + y];
                    }
                }
            }
            chunk.set_section(
                section,
                Some(SubChunk::from_storage(PalettedStorage::from_ids(&ids))),
            );
        }
        world.load_chunk(cx, cz, chunk).unwrap();
    }
    Arc::new(world)
}

fn int(v: &Value) -> i32 {
    v.as_i64().unwrap() as i32
}

fn build_goal(spec: &Value) -> Arc<dyn Goal> {
    let i = |key: &str| int(&spec[key]);
    let p = || BetterBlockPos::new(i("x"), i("y"), i("z"));
    match spec["kind"].as_str().unwrap() {
        "GoalBlock" => Arc::new(GoalBlock::new(i("x"), i("y"), i("z"))),
        "GoalTwoBlocks" => Arc::new(GoalTwoBlocks::new(i("x"), i("y"), i("z"))),
        "GoalGetToBlock" => Arc::new(GoalGetToBlock::new(p())),
        "GoalNear" => Arc::new(GoalNear::new(p(), i("range"))),
        "GoalXZ" => Arc::new(GoalXZ::new(i("x"), i("z"))),
        "GoalYLevel" => Arc::new(GoalYLevel::new(i("level"))),
        "GoalAxis" => Arc::new(GoalAxis::new()),
        "GoalStrictDirection" => Arc::new(GoalStrictDirection::new(
            p(),
            Direction::by_name(spec["direction"].as_str().unwrap()).unwrap(),
        )),
        "GoalRunAway" => {
            let from = spec["from"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| BetterBlockPos::new(int(&r[0]), int(&r[1]), int(&r[2])))
                .collect();
            let maintain_y = spec["maintain_y"].as_i64().map(|v| v as i32);
            Arc::new(GoalRunAway::new(
                dbl(spec["distance"].as_i64().unwrap()),
                maintain_y,
                from,
            ))
        }
        "GoalComposite" => Arc::new(GoalComposite::new(
            spec["goals"]
                .as_array()
                .unwrap()
                .iter()
                .map(build_goal)
                .collect(),
        )),
        "GoalInverted" => Arc::new(GoalInverted::new(build_goal(&spec["origin"]))),
        kind => panic!("unknown goal kind {kind}"),
    }
}

/// A previous path, as far as `Favoring` reads it.
#[derive(Debug)]
struct PositionsPath {
    positions: Vec<BetterBlockPos>,
    goal: Arc<dyn Goal>,
}

impl IPath for PositionsPath {
    fn movements(&self) -> &[Movement] {
        unimplemented!()
    }

    fn positions(&self) -> &[BetterBlockPos] {
        &self.positions
    }

    fn get_goal(&self) -> &Arc<dyn Goal> {
        &self.goal
    }

    fn get_num_nodes_considered(&self) -> i32 {
        unimplemented!()
    }
}

fn positions(flat: &[i32]) -> Vec<BetterBlockPos> {
    flat.chunks(3)
        .map(|p| BetterBlockPos::new(p[0], p[1], p[2]))
        .collect()
}

#[track_caller]
fn assert_no_mismatches(mismatches: &[String], total: usize) {
    if !mismatches.is_empty() {
        let shown: Vec<_> = mismatches.iter().take(30).map(String::as_str).collect();
        panic!(
            "{} of {total} checks differ from upstream, first {}:\n{}",
            mismatches.len(),
            shown.len(),
            shown.join("\n")
        );
    }
}

#[test]
fn fixture_is_for_pinned_upstream() {
    let upstream = include_str!("../UPSTREAM").trim();
    assert_eq!(
        FIXTURE.upstream, upstream,
        "regenerate with tools/refgen/run.sh"
    );
    assert_eq!(FIXTURE.minecraft, "26.3");
}

#[test]
fn configs_are_ported_settings() {
    let names = serde_json::to_value(Settings::default()).unwrap();
    for (name, config) in &FIXTURE.configs {
        for key in config.as_object().unwrap().keys() {
            assert!(
                names.get(key).is_some(),
                "config {name} sets {key}, which the port does not have"
            );
        }
    }
}

#[test]
fn tool_set_matches_upstream() {
    let mut mismatches = Vec::new();
    let mut total = 0;
    for case in &FIXTURE.tool_set {
        let _settings = with_config(&case.config);
        let tools = ToolSet::new(player(&case.player), Arc::clone(&TABLE));
        for &(id, bits, slot, slot_silk) in &case.values {
            let state = TABLE.get(id);
            total += 1;
            let got = (
                tools.get_str_vs_block(state).to_bits() as i64,
                tools.get_best_slot(state, false),
                tools.get_best_slot(state, true),
            );
            if got != (bits, slot, slot_silk) {
                mismatches.push(format!(
                    "config {}, {:?}: {} = ({}, {}, {}), upstream ({}, {slot}, {slot_silk})",
                    case.config,
                    case.player,
                    state.name,
                    f64::from_bits(got.0 as u64),
                    got.1,
                    got.2,
                    dbl(bits)
                ));
            }
        }
    }
    assert_no_mismatches(&mismatches, total);
}

#[test]
fn moves_match_upstream() {
    let mut mismatches = Vec::new();
    let mut total = 0;
    for (index, w) in FIXTURE.worlds.iter().enumerate() {
        let world = build_world(w);
        for sample in &w.move_samples {
            let _settings = with_config(&sample.config);
            let context = CalculationContext::new(
                Arc::clone(&world),
                player(&sample.player),
                sample.player.throwaway,
                true,
            );
            let mut res = MutableMoveResult::new();
            for (x, y, z, expected) in &sample.positions {
                let mut got = Vec::new();
                for (ordinal, moves) in Moves::VALUES.iter().enumerate() {
                    res.reset();
                    moves.apply(&context, *x, *y, *z, &mut res);
                    if res.cost < COST_INF {
                        got.push((ordinal, res.x, res.y, res.z, res.cost.to_bits() as i64));
                    }
                }
                total += 1;
                if got != *expected {
                    let describe = |r: &[MoveResult]| {
                        let mut s = String::new();
                        for (m, x, y, z, bits) in r {
                            write!(s, " {}->({x},{y},{z}):{}", Moves::VALUES[*m], dbl(*bits))
                                .unwrap();
                        }
                        s
                    };
                    mismatches.push(format!(
                        "world {index} ({}), config {}, {:?}, at ({x}, {y}, {z}):\n  got     {}\n  upstream{}",
                        w.kind,
                        sample.config,
                        sample.player,
                        describe(&got),
                        describe(expected)
                    ));
                }
            }
        }
    }
    assert_no_mismatches(&mismatches, total);
}

#[test]
fn paths_match_upstream() {
    let mut mismatches = Vec::new();
    let mut total = 0;
    for (index, w) in FIXTURE.worlds.iter().enumerate() {
        let world = build_world(w);
        for (qi, q) in w.queries.iter().enumerate() {
            let _settings = with_config(&q.config);
            let context = CalculationContext::new(
                Arc::clone(&world),
                player(&q.player),
                q.player.throwaway,
                true,
            );
            let where_ = format!("world {index} ({}), query {qi}", w.kind);
            total += 1;
            let got_ctx = (
                context.has_throwaway,
                context.has_water_bucket,
                context.can_sprint,
                context.water_walk_speed.to_bits() as i64,
            );
            let want_ctx = (
                q.context.has_throwaway,
                q.context.has_water_bucket,
                q.context.can_sprint,
                q.context.water_walk_speed,
            );
            if got_ctx != want_ctx {
                mismatches.push(format!(
                    "{where_}: context {got_ctx:?}, upstream {want_ctx:?}"
                ));
                continue;
            }

            let goal = build_goal(&q.goal);
            let previous = q.favoring.as_ref().map(|flat| PositionsPath {
                positions: positions(flat),
                goal: Arc::clone(&goal),
            });
            let avoidances: Vec<Avoidance> = q
                .avoidances
                .iter()
                .map(|&(x, y, z, coefficient, radius)| {
                    Avoidance::new(x, y, z, dbl(coefficient), radius)
                })
                .collect();
            let favoring = Favoring::with_avoidances(
                previous.as_ref().map(|p| p as &dyn IPath),
                &context,
                &avoidances,
            );
            let [rx, ry, rz] = q.real_start;
            let [sx, sy, sz] = q.start;
            let mut finder = AStarPathFinder::new(
                BetterBlockPos::new(rx, ry, rz),
                sx,
                sy,
                sz,
                goal,
                favoring,
                context,
            );
            let result = finder.calculate(FIXTURE.timeout, FIXTURE.timeout);
            let type_ = match result.get_type() {
                Type::SuccessToGoal => "SUCCESS_TO_GOAL",
                Type::SuccessSegment => "SUCCESS_SEGMENT",
                Type::Failure => "FAILURE",
                Type::Cancellation => "CANCELLATION",
                Type::Exception => "EXCEPTION",
            };
            if type_ != q.result.type_ {
                mismatches.push(format!(
                    "{where_}: result {type_}, upstream {}",
                    q.result.type_
                ));
                continue;
            }
            let Some(path) = result.get_path() else {
                continue;
            };
            let want_positions = positions(q.result.positions.as_ref().unwrap());
            if path.positions() != want_positions {
                mismatches.push(format!(
                    "{where_}: positions {:?}\n  upstream {:?}",
                    path.positions(),
                    want_positions
                ));
                continue;
            }
            let got_movements: Vec<(String, i64, bool)> = path
                .movements()
                .iter()
                .map(|m| {
                    (
                        m.class_name().to_owned(),
                        m.get_cost().to_bits() as i64,
                        m.calculated_while_loaded(),
                    )
                })
                .collect();
            let want_movements = q.result.movements.as_ref().unwrap();
            if got_movements != *want_movements {
                for (i, (got, want)) in got_movements.iter().zip(want_movements).enumerate() {
                    if got != want {
                        mismatches.push(format!(
                            "{where_}: movement {i} from {} is ({}, {}, {}), upstream ({}, {}, {})",
                            path.positions()[i],
                            got.0,
                            dbl(got.1),
                            got.2,
                            want.0,
                            dbl(want.1),
                            want.2
                        ));
                        break;
                    }
                }
                continue;
            }
            if Some(path.get_num_nodes_considered()) != q.result.num_nodes {
                mismatches.push(format!(
                    "{where_}: {} nodes considered, upstream {:?}",
                    path.get_num_nodes_considered(),
                    q.result.num_nodes
                ));
            }
        }
    }
    assert_no_mismatches(&mismatches, total);
}
