//! Replays `fixtures/reference/math_goals.json`, generated by `tools/refgen/run.sh` from the
//! real upstream classes running against the real Minecraft client. Floating point values are
//! compared bit for bit (any NaN matches any NaN).

// Upstream runs on Java Edition, with its costs.
#![cfg(not(feature = "bedrock"))]

use std::sync::{Arc, LazyLock};

use baritone::api::pathing::goals::{
    Goal, GoalAxis, GoalBlock, GoalComposite, GoalGetToBlock, GoalInverted, GoalNear, GoalRunAway,
    GoalStrictDirection, GoalTwoBlocks, GoalXZ, GoalYLevel,
};
use baritone::api::pathing::movement::{ActionCosts, COST_INF, action_costs};
use baritone::api::utils::{BetterBlockPos, Rotation, rotation_utils};
use baritone::mc::{Direction, Vec3, mth};
use baritone::utils::baritone_math;
use serde_json::Value;

static FIXTURE: LazyLock<Value> = LazyLock::new(|| {
    serde_json::from_str(include_str!("fixtures/reference/math_goals.json")).unwrap()
});

fn section(name: &str) -> &'static Value {
    &FIXTURE[name]
}

fn rows(section_name: &str, key: &str) -> &'static [Value] {
    let rows = section(section_name)[key]
        .as_array()
        .unwrap_or_else(|| panic!("missing {section_name}.{key}"));
    assert!(!rows.is_empty(), "{section_name}.{key} is empty");
    rows
}

fn int(v: &Value) -> i32 {
    i32::try_from(v.as_i64().unwrap()).unwrap()
}

fn long(v: &Value) -> i64 {
    v.as_i64().unwrap()
}

fn dbl(v: &Value) -> f64 {
    f64::from_bits(v.as_i64().unwrap() as u64)
}

fn flt(v: &Value) -> f32 {
    f32::from_bits(int(v) as u32)
}

fn boolean(v: &Value) -> bool {
    v.as_bool().unwrap()
}

#[track_caller]
fn assert_f64(actual: f64, expected: f64, context: &dyn std::fmt::Debug) {
    if expected.is_nan() {
        assert!(actual.is_nan(), "{context:?}: expected NaN, got {actual}");
    } else {
        assert_eq!(
            actual.to_bits(),
            expected.to_bits(),
            "{context:?}: expected {expected:e}, got {actual:e}"
        );
    }
}

#[track_caller]
fn assert_f32(actual: f32, expected: f32, context: &dyn std::fmt::Debug) {
    if expected.is_nan() {
        assert!(actual.is_nan(), "{context:?}: expected NaN, got {actual}");
    } else {
        assert_eq!(
            actual.to_bits(),
            expected.to_bits(),
            "{context:?}: expected {expected:e}, got {actual:e}"
        );
    }
}

fn pos(r: &[Value], at: usize) -> BetterBlockPos {
    BetterBlockPos::new(int(&r[at]), int(&r[at + 1]), int(&r[at + 2]))
}

#[test]
fn fixture_is_for_pinned_upstream() {
    let upstream = include_str!("../UPSTREAM").trim();
    assert_eq!(
        FIXTURE["upstream"].as_str().unwrap(),
        upstream,
        "regenerate with tools/refgen/run.sh"
    );
}

// region BetterBlockPos

#[test]
fn better_block_pos_hash() {
    for r in rows("better_block_pos", "hash") {
        let r = r.as_array().unwrap();
        let p = pos(r, 0);
        assert_eq!(
            BetterBlockPos::long_hash(p.x, p.y, p.z),
            long(&r[3]),
            "{p:?}"
        );
        assert_eq!(BetterBlockPos::long_hash_pos(p), long(&r[3]), "{p:?}");
        assert_eq!(p.hash_code(), int(&r[4]), "{p:?}");
    }
}

#[test]
fn better_block_pos_serialize() {
    for r in rows("better_block_pos", "serialize") {
        let r = r.as_array().unwrap();
        let p = pos(r, 0);
        let serialized = BetterBlockPos::serialize_to_long(p.x, p.y, p.z);
        assert_eq!(serialized, long(&r[3]), "{p:?}");
        assert_eq!(
            BetterBlockPos::deserialize_from_long(serialized),
            pos(r, 4),
            "{p:?}"
        );
    }
    for r in rows("better_block_pos", "deserialize") {
        let r = r.as_array().unwrap();
        assert_eq!(
            BetterBlockPos::deserialize_from_long(long(&r[0])),
            pos(r, 1),
            "{}",
            long(&r[0])
        );
    }
}

#[test]
fn better_block_pos_from_f64() {
    for r in rows("better_block_pos", "from_double") {
        let r = r.as_array().unwrap();
        let (x, y, z) = (dbl(&r[0]), dbl(&r[1]), dbl(&r[2]));
        assert_eq!(BetterBlockPos::from_f64(x, y, z), pos(r, 3), "{x} {y} {z}");
    }
}

#[test]
fn better_block_pos_distance() {
    for r in rows("better_block_pos", "distance") {
        let r = r.as_array().unwrap();
        let (a, b) = (pos(r, 0), pos(r, 3));
        assert_f64(a.distance_sq(&b), dbl(&r[6]), &(a, b));
        assert_f64(a.distance_to(&b), dbl(&r[7]), &(a, b));
    }
}

#[test]
fn better_block_pos_offsets() {
    for r in rows("better_block_pos", "offsets") {
        let r = r.as_array().unwrap();
        let p = pos(r, 0);
        let amt = int(&r[3]);
        let mut actual = vec![
            p.above_n(amt),
            p.below_n(amt),
            p.north_n(amt),
            p.south_n(amt),
            p.east_n(amt),
            p.west_n(amt),
        ];
        actual.extend(Direction::VALUES.map(|d| p.relative_n(d, amt)));
        for (i, q) in actual.into_iter().enumerate() {
            assert_eq!(q, pos(r, 4 + i * 3), "{p:?} amt={amt} op={i}");
        }
    }
    for r in rows("better_block_pos", "unit_offsets") {
        let r = r.as_array().unwrap();
        let p = pos(r, 0);
        let mut actual = vec![
            p.above(),
            p.below(),
            p.north(),
            p.south(),
            p.east(),
            p.west(),
        ];
        actual.extend(Direction::VALUES.map(|d| p.relative(d)));
        for (i, q) in actual.into_iter().enumerate() {
            assert_eq!(q, pos(r, 3 + i * 3), "{p:?} op={i}");
        }
    }
}

#[test]
fn better_block_pos_to_string() {
    for r in rows("better_block_pos", "to_string") {
        let r = r.as_array().unwrap();
        assert_eq!(pos(r, 0).to_string(), r[3].as_str().unwrap());
    }
}

// endregion

// region Mth

#[test]
fn mth_tables() {
    let mth_section = section("mth");
    let table = mth::sin_table();
    assert_eq!(
        table.len() as i64,
        mth_section["sin_table_len"].as_i64().unwrap()
    );
    let mut h: u64 = 0xcbf29ce484222325;
    for v in table.iter() {
        h ^= v.to_bits() as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    for r in rows("mth", "sin_table_samples") {
        let r = r.as_array().unwrap();
        let i = int(&r[0]) as usize;
        assert_f32(table[i], flt(&r[1]), &i);
    }
    assert_eq!(
        h as i64,
        mth_section["sin_table_fnv"].as_i64().unwrap(),
        "SIN table differs"
    );

    for (i, v) in rows("mth", "asin_tab").iter().enumerate() {
        assert_f64(mth::asin_tab()[i], dbl(v), &("ASIN_TAB", i));
    }
    for (i, v) in rows("mth", "cos_tab").iter().enumerate() {
        assert_f64(mth::cos_tab()[i], dbl(v), &("COS_TAB", i));
    }
    assert_f64(
        mth::frac_bias(),
        dbl(&mth_section["frac_bias"]),
        &"FRAC_BIAS",
    );
}

#[test]
fn mth_sin_cos() {
    for r in rows("mth", "sin_cos") {
        let r = r.as_array().unwrap();
        let v = dbl(&r[0]);
        assert_f32(mth::sin(v), flt(&r[1]), &("sin", v));
        assert_f32(mth::cos(v), flt(&r[2]), &("cos", v));
    }
}

#[test]
fn mth_atan2() {
    for r in rows("mth", "atan2") {
        let r = r.as_array().unwrap();
        let (y, x) = (dbl(&r[0]), dbl(&r[1]));
        assert_f64(mth::atan2(y, x), dbl(&r[2]), &(y, x));
    }
    for r in rows("mth", "fast_inv_sqrt") {
        let r = r.as_array().unwrap();
        let v = dbl(&r[0]);
        assert_f64(mth::fast_inv_sqrt(v), dbl(&r[1]), &v);
    }
}

#[test]
fn mth_floor_wrap_degrees() {
    for r in rows("mth", "floor") {
        let r = r.as_array().unwrap();
        let v = dbl(&r[0]);
        assert_eq!(mth::floor(v), int(&r[1]), "{v}");
    }
    for r in rows("mth", "wrap_degrees_f32") {
        let r = r.as_array().unwrap();
        let v = flt(&r[0]);
        assert_f32(mth::wrap_degrees(v), flt(&r[1]), &v);
    }
    for r in rows("mth", "wrap_degrees_f64") {
        let r = r.as_array().unwrap();
        let v = dbl(&r[0]);
        assert_f64(mth::wrap_degrees_f64(v), dbl(&r[1]), &v);
    }
}

// endregion

// region ActionCosts, BaritoneMath

#[test]
fn action_costs_constants() {
    let s = section("action_costs");
    let c = ActionCosts::java();
    let expected = [
        ("WALK_ONE_BLOCK_COST", c.walk_one_block_cost),
        ("WALK_ONE_IN_WATER_COST", c.walk_one_in_water_cost),
        (
            "WALK_ONE_OVER_SOUL_SAND_COST",
            c.walk_one_over_soul_sand_cost,
        ),
        ("LADDER_UP_ONE_COST", c.ladder_up_one_cost),
        ("LADDER_DOWN_ONE_COST", c.ladder_down_one_cost),
        ("SNEAK_ONE_BLOCK_COST", c.sneak_one_block_cost),
        ("SPRINT_ONE_BLOCK_COST", c.sprint_one_block_cost),
        ("SPRINT_MULTIPLIER", c.sprint_multiplier),
        ("WALK_OFF_BLOCK_COST", c.walk_off_block_cost),
        ("CENTER_AFTER_FALL_COST", c.center_after_fall_cost),
        ("COST_INF", COST_INF),
        ("FALL_1_25_BLOCKS_COST", c.fall_1_25_blocks_cost),
        ("FALL_0_25_BLOCKS_COST", c.fall_0_25_blocks_cost),
        ("JUMP_ONE_BLOCK_COST", c.jump_one_block_cost),
    ];
    for (name, actual) in expected {
        assert_f64(actual, dbl(&s[name]), &name);
    }
    let fall = rows("action_costs", "FALL_N_BLOCKS_COST");
    assert_eq!(c.fall_n_blocks_cost.len(), fall.len());
    for (i, v) in fall.iter().enumerate() {
        assert_f64(c.fall_n_blocks_cost[i], dbl(v), &("FALL_N_BLOCKS_COST", i));
    }
    assert_eq!(
        **action_costs(),
        c,
        "default active costs are the Java costs"
    );
}

#[test]
fn action_costs_functions() {
    for r in rows("action_costs", "velocity") {
        let r = r.as_array().unwrap();
        let t = int(&r[0]);
        assert_f64(ActionCosts::velocity(t), dbl(&r[1]), &t);
    }
    for r in rows("action_costs", "old_formula") {
        let r = r.as_array().unwrap();
        let t = dbl(&r[0]);
        assert_f64(ActionCosts::old_formula(t), dbl(&r[1]), &t);
    }
    for r in rows("action_costs", "distance_to_ticks") {
        let r = r.as_array().unwrap();
        let d = dbl(&r[0]);
        assert_f64(ActionCosts::distance_to_ticks(d), dbl(&r[1]), &d);
    }
}

#[test]
fn baritone_math_fast_floor_ceil() {
    for r in rows("baritone_math", "fast_floor_ceil") {
        let r = r.as_array().unwrap();
        let v = dbl(&r[0]);
        assert_eq!(baritone_math::fast_floor(v), int(&r[1]), "fastFloor({v})");
        assert_eq!(baritone_math::fast_ceil(v), int(&r[2]), "fastCeil({v})");
    }
}

// endregion

// region Rotation, RotationUtils

#[test]
fn rotation_statics() {
    for r in rows("rotation", "normalize_clamp") {
        let r = r.as_array().unwrap();
        let v = flt(&r[0]);
        assert_f32(Rotation::normalize_yaw(v), flt(&r[1]), &("normalizeYaw", v));
        assert_f32(Rotation::clamp_pitch(v), flt(&r[2]), &("clampPitch", v));
    }
    for r in rows("rotation", "yaw_distance_from_offset") {
        let r = r.as_array().unwrap();
        let (a, b) = (flt(&r[0]), flt(&r[1]));
        assert_f32(
            Rotation::yaw_distance_from_offset(a, b),
            flt(&r[2]),
            &(a, b),
        );
    }
}

#[test]
fn rotation_pairs() {
    for r in rows("rotation", "pairs") {
        let r = r.as_array().unwrap();
        let a = Rotation::new(flt(&r[0]), flt(&r[1]));
        let b = Rotation::new(flt(&r[2]), flt(&r[3]));
        let ctx = (a, b);
        let add = a.add(&b);
        assert_f32(add.get_yaw(), flt(&r[4]), &ctx);
        assert_f32(add.get_pitch(), flt(&r[5]), &ctx);
        let sub = a.subtract(&b);
        assert_f32(sub.get_yaw(), flt(&r[6]), &ctx);
        assert_f32(sub.get_pitch(), flt(&r[7]), &ctx);
        let nc = a.normalize_and_clamp();
        assert_f32(nc.get_yaw(), flt(&r[8]), &ctx);
        assert_f32(nc.get_pitch(), flt(&r[9]), &ctx);
        assert_eq!(a.is_really_close_to(&b), boolean(&r[10]), "{ctx:?}");
        assert_eq!(a.yaw_is_really_close(&b), boolean(&r[11]), "{ctx:?}");
    }
}

fn vec3(r: &[Value], at: usize) -> Vec3 {
    Vec3::new(dbl(&r[at]), dbl(&r[at + 1]), dbl(&r[at + 2]))
}

#[test]
fn rotation_utils_calc_rotation() {
    for r in rows("rotation_utils", "calc_rotation_from_vec3d") {
        let r = r.as_array().unwrap();
        let (orig, dest) = (vec3(r, 0), vec3(r, 3));
        let current = Rotation::new(flt(&r[6]), flt(&r[7]));
        let ctx = (orig, dest, current);
        let plain = rotation_utils::calc_rotation_from_vec3d_absolute(orig, dest);
        assert_f32(plain.get_yaw(), flt(&r[8]), &ctx);
        assert_f32(plain.get_pitch(), flt(&r[9]), &ctx);
        let relative = rotation_utils::calc_rotation_from_vec3d(orig, dest, current);
        assert_f32(relative.get_yaw(), flt(&r[10]), &ctx);
        assert_f32(relative.get_pitch(), flt(&r[11]), &ctx);
    }
    for r in rows("rotation_utils", "calc_rotation_from_coords") {
        let r = r.as_array().unwrap();
        let (orig, dest) = (pos(r, 0), pos(r, 3));
        let rotation = rotation_utils::calc_rotation_from_coords(orig, dest);
        assert_f32(rotation.get_yaw(), flt(&r[6]), &(orig, dest));
        assert_f32(rotation.get_pitch(), flt(&r[7]), &(orig, dest));
    }
}

#[test]
fn rotation_utils_look_direction() {
    for r in rows("rotation_utils", "calc_look_direction_from_rotation") {
        let r = r.as_array().unwrap();
        let rotation = Rotation::new(flt(&r[0]), flt(&r[1]));
        let v = rotation_utils::calc_look_direction_from_rotation(rotation);
        assert_f64(v.x, dbl(&r[2]), &rotation);
        assert_f64(v.y, dbl(&r[3]), &rotation);
        assert_f64(v.z, dbl(&r[4]), &rotation);
    }
}

// endregion

// region goals

fn build_goal(spec: &Value) -> Arc<dyn Goal> {
    let i = |key: &str| int(&spec[key]);
    let p = || BetterBlockPos::new(i("x"), i("y"), i("z"));
    match spec["kind"].as_str().unwrap() {
        "GoalBlock" => Arc::new(GoalBlock::new(i("x"), i("y"), i("z"))),
        "GoalTwoBlocks" => Arc::new(GoalTwoBlocks::new(i("x"), i("y"), i("z"))),
        "GoalGetToBlock" => Arc::new(GoalGetToBlock::new(p())),
        "GoalNear" => Arc::new(GoalNear::new(p(), i("range"))),
        "GoalXZ" => Arc::new(GoalXZ::new(i("x"), i("z"))),
        "GoalYLevel" => Arc::new(GoalYLevel::new(i("level"))),
        "GoalAxis" => Arc::new(GoalAxis::new()),
        "GoalStrictDirection" => Arc::new(GoalStrictDirection::new(
            p(),
            Direction::by_name(spec["direction"].as_str().unwrap()).unwrap(),
        )),
        "GoalRunAway" => {
            let from = spec["from"]
                .as_array()
                .unwrap()
                .iter()
                .map(|r| pos(r.as_array().unwrap(), 0))
                .collect();
            let maintain_y = spec["maintain_y"].as_i64().map(|v| v as i32);
            Arc::new(GoalRunAway::new(dbl(&spec["distance"]), maintain_y, from))
        }
        "GoalComposite" => Arc::new(GoalComposite::new(
            spec["goals"]
                .as_array()
                .unwrap()
                .iter()
                .map(build_goal)
                .collect(),
        )),
        "GoalInverted" => Arc::new(GoalInverted::new(build_goal(&spec["origin"]))),
        kind => panic!("unknown goal kind {kind}"),
    }
}

#[test]
fn goals() {
    let cases = FIXTURE["goals"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let goal = build_goal(&case["spec"]);
        assert_eq!(goal.to_string(), case["to_string"].as_str().unwrap());
        assert_f64(
            goal.heuristic_at_goal(),
            dbl(&case["heuristic_at_goal"]),
            &goal,
        );
        for r in case["samples"].as_array().unwrap() {
            let r = r.as_array().unwrap();
            let p = pos(r, 0);
            assert_eq!(
                goal.is_in_goal(p.x, p.y, p.z),
                boolean(&r[3]),
                "{goal} at {p:?}"
            );
            assert_eq!(goal.is_in_goal_pos(p), boolean(&r[3]), "{goal} at {p:?}");
            assert_f64(
                goal.heuristic(p.x, p.y, p.z),
                dbl(&r[4]),
                &(goal.to_string(), p),
            );
            assert_f64(goal.heuristic_pos(p), dbl(&r[4]), &(goal.to_string(), p));
        }
    }
}

#[test]
fn goal_statics() {
    for r in rows("goal_statics", "goal_block_calculate") {
        let r = r.as_array().unwrap();
        let (x, y, z) = (dbl(&r[0]), int(&r[1]), dbl(&r[2]));
        assert_f64(GoalBlock::calculate(x, y, z), dbl(&r[3]), &(x, y, z));
    }
    for r in rows("goal_statics", "goal_xz_calculate") {
        let r = r.as_array().unwrap();
        let (x, z) = (dbl(&r[0]), dbl(&r[1]));
        assert_f64(GoalXZ::calculate(x, z), dbl(&r[2]), &(x, z));
    }
    for r in rows("goal_statics", "goal_y_level_calculate") {
        let r = r.as_array().unwrap();
        let (goal_y, current_y) = (int(&r[0]), int(&r[1]));
        assert_f64(
            GoalYLevel::calculate(goal_y, current_y),
            dbl(&r[2]),
            &(goal_y, current_y),
        );
    }
    for r in rows("goal_statics", "goal_xz_from_direction") {
        let r = r.as_array().unwrap();
        let (origin, yaw, distance) = (vec3(r, 0), flt(&r[3]), dbl(&r[4]));
        let goal = GoalXZ::from_direction(origin, yaw, distance);
        assert_eq!(
            (goal.get_x(), goal.get_z()),
            (int(&r[5]), int(&r[6])),
            "{origin:?} {yaw} {distance}"
        );
    }
}

// endregion
