package refgen;

import baritone.api.pathing.goals.Goal;
import baritone.api.pathing.goals.GoalAxis;
import baritone.api.pathing.goals.GoalBlock;
import baritone.api.pathing.goals.GoalComposite;
import baritone.api.pathing.goals.GoalGetToBlock;
import baritone.api.pathing.goals.GoalInverted;
import baritone.api.pathing.goals.GoalNear;
import baritone.api.pathing.goals.GoalRunAway;
import baritone.api.pathing.goals.GoalStrictDirection;
import baritone.api.pathing.goals.GoalTwoBlocks;
import baritone.api.pathing.goals.GoalXZ;
import baritone.api.pathing.goals.GoalYLevel;
import baritone.api.pathing.movement.ActionCosts;
import baritone.api.utils.BetterBlockPos;
import baritone.api.utils.Rotation;
import baritone.utils.BaritoneMath;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonNull;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.util.Mth;
import net.minecraft.world.phys.Vec3;

import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Generates reference values for the Rust port by running the real upstream classes (compiled
 * against the real Minecraft client jar).
 * <p>
 * Floating point values are written as raw bits ({@code long} for double, {@code int} for float)
 * so the Rust side can compare exactly, including NaN/infinity.
 */
public final class RefGen {

    private static final Random R = new Random(0x6a09e667L);

    private static final int[] INT_EDGES = {
            0, 1, -1, 2, -2, 15, 16, -16, 64, -64, 255, 256, 319, 320, -2048, 2047,
            30_000_000, -30_000_000, 33_554_431, 33_554_432, -33_554_432, -33_554_433,
            Integer.MAX_VALUE, Integer.MIN_VALUE, Integer.MAX_VALUE - 1, Integer.MIN_VALUE + 1
    };

    private static final double[] DOUBLE_EDGES = {
            0.0, -0.0, 0.5, -0.5, 1e-9, -1e-9, Math.nextDown(1.0), -Math.nextDown(1.0), 1.0, -1.0,
            123.456, -123.456, 2147483647.5, -2147483648.5, 2147483648.0, -2147483649.0, 1e300, -1e300,
            Double.MIN_VALUE, -Double.MIN_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE,
            Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY
    };

    private RefGen() {}

    public static void main(String[] args) throws Exception {
        JsonObject root = new JsonObject();
        root.addProperty("upstream", args[0]);
        root.addProperty("minecraft", args[1]);
        root.add("better_block_pos", betterBlockPos());
        root.add("mth", mth());
        root.add("action_costs", actionCosts());
        root.add("baritone_math", baritoneMath());
        root.add("rotation", rotation());
        root.add("rotation_utils", rotationUtils());
        root.add("goals", goals());
        root.add("goal_statics", goalStatics());
        Files.writeString(Path.of(args[2]), new Gson().toJson(root) + "\n");
        Files.writeString(Path.of(args[3]), mthTables(args[1]));
    }

    /**
     * Mth.ASIN_TAB and Mth.COS_TAB as Rust source. Java fills them with StrictMath.asin (fdlibm)
     * and the HotSpot Math.cos intrinsic; no single Rust libm reproduces both, so the port embeds
     * the values.
     */
    private static String mthTables(String minecraft) throws ReflectiveOperationException {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by tools/refgen/run.sh from Minecraft ").append(minecraft)
                .append(" net/minecraft/util/Mth.java. Do not edit.\n");
        sb.append("//\n");
        sb.append("// Java fills these with StrictMath.asin (fdlibm) and the HotSpot Math.cos intrinsic. No single\n");
        sb.append("// Rust libm reproduces both bit for bit, so the values are embedded.\n\n");
        for (String name : new String[]{"ASIN_TAB", "COS_TAB"}) {
            double[] table = (double[]) staticField(Mth.class, name);
            sb.append("pub(super) static ").append(name).append(": [f64; ").append(table.length).append("] = [\n");
            for (double v : table) {
                sb.append(String.format("    f64::from_bits(0x%016x), // %s%n", Double.doubleToRawLongBits(v), v));
            }
            sb.append("];\n");
            if (name.equals("ASIN_TAB")) {
                sb.append("\n");
            }
        }
        return sb.toString();
    }

    // region helpers

    private static JsonPrimitive d(double v) {
        return new JsonPrimitive(Double.doubleToRawLongBits(v));
    }

    private static JsonPrimitive f(float v) {
        return new JsonPrimitive(Float.floatToRawIntBits(v));
    }

    private static JsonArray row(Object... values) {
        JsonArray a = new JsonArray();
        for (Object v : values) {
            if (v instanceof JsonElement e) {
                a.add(e);
            } else if (v instanceof Boolean b) {
                a.add(b);
            } else if (v instanceof Number n) {
                a.add(n);
            } else if (v instanceof String s) {
                a.add(s);
            } else {
                throw new IllegalArgumentException(String.valueOf(v));
            }
        }
        return a;
    }

    private static JsonArray pos(BlockPos p) {
        return row(p.getX(), p.getY(), p.getZ());
    }

    private static int randInt() {
        return switch (R.nextInt(4)) {
            case 0 -> INT_EDGES[R.nextInt(INT_EDGES.length)];
            case 1 -> R.nextInt(64) - 32;
            case 2 -> R.nextInt(60_000_001) - 30_000_000;
            default -> R.nextInt();
        };
    }

    private static double randDouble() {
        return switch (R.nextInt(4)) {
            case 0 -> DOUBLE_EDGES[R.nextInt(DOUBLE_EDGES.length)];
            case 1 -> (R.nextDouble() - 0.5) * 64;
            case 2 -> (R.nextDouble() - 0.5) * 2e4;
            default -> (R.nextDouble() - 0.5) * 2e9;
        };
    }

    private static double randFiniteDouble() {
        double v;
        do {
            v = randDouble();
        } while (!Double.isFinite(v));
        return v;
    }

    private static float randAngle() {
        return switch (R.nextInt(5)) {
            case 0 -> new float[]{0F, -0F, 90F, -90F, 180F, -180F, 360F, -360F, 540F, -540F, 179.995F, 359.995F, 0.005F}[R.nextInt(13)];
            case 1 -> (R.nextFloat() - 0.5F) * 360F;
            case 2 -> (R.nextFloat() - 0.5F) * 720F;
            case 3 -> (R.nextFloat() - 0.5F) * 20000F;
            default -> (R.nextFloat() - 0.5F) * 200F;
        };
    }

    private static Object staticField(Class<?> clazz, String name) throws ReflectiveOperationException {
        Field field = clazz.getDeclaredField(name);
        field.setAccessible(true);
        return field.get(null);
    }

    // endregion

    private static JsonObject betterBlockPos() {
        JsonObject o = new JsonObject();

        // [x, y, z, longHash, hashCode]
        JsonArray hashes = new JsonArray();
        for (int i = 0; i < 300; i++) {
            int x = randInt(), y = randInt(), z = randInt();
            hashes.add(row(x, y, z, BetterBlockPos.longHash(x, y, z), new BetterBlockPos(x, y, z).hashCode()));
        }
        o.add("hash", hashes);

        // [x, y, z, serializeToLong, deserialized x, y, z]
        JsonArray serialize = new JsonArray();
        for (int i = 0; i < 300; i++) {
            int x = randInt(), y = randInt(), z = randInt();
            long s = BetterBlockPos.serializeToLong(x, y, z);
            BetterBlockPos back = BetterBlockPos.deserializeFromLong(s);
            serialize.add(row(x, y, z, s, back.x, back.y, back.z));
        }
        o.add("serialize", serialize);

        // [serialized, x, y, z] for arbitrary longs
        JsonArray deserialize = new JsonArray();
        for (int i = 0; i < 100; i++) {
            long s = R.nextLong();
            BetterBlockPos p = BetterBlockPos.deserializeFromLong(s);
            deserialize.add(row(s, p.x, p.y, p.z));
        }
        o.add("deserialize", deserialize);

        // [x, y, z (double bits), x, y, z]
        JsonArray fromDouble = new JsonArray();
        for (int i = 0; i < 200; i++) {
            double x = randDouble(), y = randDouble(), z = randDouble();
            BetterBlockPos p = new BetterBlockPos(x, y, z);
            fromDouble.add(row(d(x), d(y), d(z), p.x, p.y, p.z));
        }
        o.add("from_double", fromDouble);

        // [x1, y1, z1, x2, y2, z2, distanceSq, distanceTo]
        JsonArray distance = new JsonArray();
        for (int i = 0; i < 200; i++) {
            BetterBlockPos a = new BetterBlockPos(randInt(), randInt(), randInt());
            BetterBlockPos b = new BetterBlockPos(randInt(), randInt(), randInt());
            distance.add(row(a.x, a.y, a.z, b.x, b.y, b.z, d(a.distanceSq(b)), d(a.distanceTo(b))));
        }
        o.add("distance", distance);

        // [x, y, z, amt, above(amt), below(amt), north(amt), south(amt), east(amt), west(amt),
        //  relative(DOWN..EAST, amt)...] each result flattened as x, y, z
        JsonArray offsets = new JsonArray();
        for (int i = 0; i < 200; i++) {
            BetterBlockPos p = new BetterBlockPos(randInt(), randInt(), randInt());
            int amt = i % 4 == 0 ? 1 : randInt();
            JsonArray r = row(p.x, p.y, p.z, amt);
            List<BetterBlockPos> results = new ArrayList<>(List.of(
                    p.above(amt), p.below(amt), p.north(amt), p.south(amt), p.east(amt), p.west(amt)));
            for (Direction dir : Direction.values()) {
                results.add(p.relative(dir, amt));
            }
            for (BetterBlockPos q : results) {
                r.add(q.x);
                r.add(q.y);
                r.add(q.z);
            }
            offsets.add(r);
        }
        o.add("offsets", offsets);

        // unit offsets: [x, y, z, above(), below(), north(), south(), east(), west(), relative(DOWN..EAST)...]
        JsonArray unit = new JsonArray();
        for (int i = 0; i < 50; i++) {
            BetterBlockPos p = new BetterBlockPos(randInt(), randInt(), randInt());
            JsonArray r = row(p.x, p.y, p.z);
            List<BetterBlockPos> results = new ArrayList<>(List.of(
                    p.above(), p.below(), p.north(), p.south(), p.east(), p.west()));
            for (Direction dir : Direction.values()) {
                results.add(p.relative(dir));
            }
            for (BetterBlockPos q : results) {
                r.add(q.x);
                r.add(q.y);
                r.add(q.z);
            }
            unit.add(r);
        }
        o.add("unit_offsets", unit);

        JsonArray strings = new JsonArray();
        for (BetterBlockPos p : new BetterBlockPos[]{BetterBlockPos.ORIGIN, new BetterBlockPos(-12, 345, Integer.MIN_VALUE)}) {
            strings.add(row(p.x, p.y, p.z, p.toString()));
        }
        o.add("to_string", strings);
        return o;
    }

    private static JsonObject mth() throws ReflectiveOperationException {
        JsonObject o = new JsonObject();

        float[] sinTable = (float[]) staticField(Mth.class, "SIN");
        // FNV-1a over the raw bits of each entry, one 32 bit word at a time
        long h = 0xcbf29ce484222325L;
        for (float v : sinTable) {
            h ^= Float.floatToRawIntBits(v) & 0xFFFFFFFFL;
            h *= 0x100000001b3L;
        }
        o.addProperty("sin_table_len", sinTable.length);
        o.addProperty("sin_table_fnv", h);
        JsonArray sinSamples = new JsonArray();
        for (int i = 0; i < 512; i++) {
            int idx = i < 16 ? i * 4096 : R.nextInt(sinTable.length);
            sinSamples.add(row(idx, f(sinTable[idx])));
        }
        o.add("sin_table_samples", sinSamples);

        JsonArray asinTab = new JsonArray();
        for (double v : (double[]) staticField(Mth.class, "ASIN_TAB")) {
            asinTab.add(d(v));
        }
        o.add("asin_tab", asinTab);
        JsonArray cosTab = new JsonArray();
        for (double v : (double[]) staticField(Mth.class, "COS_TAB")) {
            cosTab.add(d(v));
        }
        o.add("cos_tab", cosTab);
        o.add("frac_bias", d((double) staticField(Mth.class, "FRAC_BIAS")));

        // [in, sin, cos]
        JsonArray sinCos = new JsonArray();
        for (int i = 0; i < 400; i++) {
            double v = i < 100 ? (R.nextDouble() - 0.5) * 20 : randDouble();
            sinCos.add(row(d(v), f(Mth.sin(v)), f(Mth.cos(v))));
        }
        o.add("sin_cos", sinCos);

        // [y, x, atan2]
        JsonArray atan2 = new JsonArray();
        double[] specials = {0.0, -0.0, 1.0, -1.0, 1e-300, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, Double.NaN};
        for (double y : specials) {
            for (double x : specials) {
                atan2.add(row(d(y), d(x), d(Mth.atan2(y, x))));
            }
        }
        for (int i = 0; i < 500; i++) {
            double y = i < 250 ? (R.nextDouble() - 0.5) * 20 : randDouble();
            double x = i < 250 ? (R.nextDouble() - 0.5) * 20 : randDouble();
            atan2.add(row(d(y), d(x), d(Mth.atan2(y, x))));
        }
        o.add("atan2", atan2);

        // [in, fastInvSqrt]
        JsonArray invSqrt = new JsonArray();
        for (int i = 0; i < 200; i++) {
            double v = i < 100 ? R.nextDouble() * 100 : randDouble();
            invSqrt.add(row(d(v), d(Mth.fastInvSqrt(v))));
        }
        o.add("fast_inv_sqrt", invSqrt);

        // [in, floor]
        JsonArray floor = new JsonArray();
        for (int i = 0; i < 300; i++) {
            double v = randDouble();
            floor.add(row(d(v), Mth.floor(v)));
        }
        o.add("floor", floor);

        // [in, wrapDegrees(float)]
        JsonArray wrapF = new JsonArray();
        for (int i = 0; i < 300; i++) {
            float v = i < 10 ? new float[]{Float.NaN, Float.POSITIVE_INFINITY, 180F, -180F, 540F, -540F, 0F, -0F, 1e20F, -1e20F}[i] : randAngle();
            wrapF.add(row(f(v), f(Mth.wrapDegrees(v))));
        }
        o.add("wrap_degrees_f32", wrapF);

        // [in, wrapDegrees(double)]
        JsonArray wrapD = new JsonArray();
        for (int i = 0; i < 300; i++) {
            double v = i % 2 == 0 ? randDouble() : randAngle();
            wrapD.add(row(d(v), d(Mth.wrapDegrees(v))));
        }
        o.add("wrap_degrees_f64", wrapD);
        return o;
    }

    private static JsonObject actionCosts() {
        JsonObject o = new JsonObject();
        o.add("WALK_ONE_BLOCK_COST", d(ActionCosts.WALK_ONE_BLOCK_COST));
        o.add("WALK_ONE_IN_WATER_COST", d(ActionCosts.WALK_ONE_IN_WATER_COST));
        o.add("WALK_ONE_OVER_SOUL_SAND_COST", d(ActionCosts.WALK_ONE_OVER_SOUL_SAND_COST));
        o.add("LADDER_UP_ONE_COST", d(ActionCosts.LADDER_UP_ONE_COST));
        o.add("LADDER_DOWN_ONE_COST", d(ActionCosts.LADDER_DOWN_ONE_COST));
        o.add("SNEAK_ONE_BLOCK_COST", d(ActionCosts.SNEAK_ONE_BLOCK_COST));
        o.add("SPRINT_ONE_BLOCK_COST", d(ActionCosts.SPRINT_ONE_BLOCK_COST));
        o.add("SPRINT_MULTIPLIER", d(ActionCosts.SPRINT_MULTIPLIER));
        o.add("WALK_OFF_BLOCK_COST", d(ActionCosts.WALK_OFF_BLOCK_COST));
        o.add("CENTER_AFTER_FALL_COST", d(ActionCosts.CENTER_AFTER_FALL_COST));
        o.add("COST_INF", d(ActionCosts.COST_INF));
        o.add("FALL_1_25_BLOCKS_COST", d(ActionCosts.FALL_1_25_BLOCKS_COST));
        o.add("FALL_0_25_BLOCKS_COST", d(ActionCosts.FALL_0_25_BLOCKS_COST));
        o.add("JUMP_ONE_BLOCK_COST", d(ActionCosts.JUMP_ONE_BLOCK_COST));

        JsonArray fall = new JsonArray();
        for (double v : ActionCosts.FALL_N_BLOCKS_COST) {
            fall.add(d(v));
        }
        o.add("FALL_N_BLOCKS_COST", fall);

        // [ticks, velocity]
        JsonArray velocity = new JsonArray();
        for (int t = -5; t < 300; t++) {
            velocity.add(row(t, d(ActionCosts.velocity(t))));
        }
        velocity.add(row(Integer.MAX_VALUE, d(ActionCosts.velocity(Integer.MAX_VALUE))));
        velocity.add(row(Integer.MIN_VALUE, d(ActionCosts.velocity(Integer.MIN_VALUE))));
        o.add("velocity", velocity);

        // [ticks, oldFormula]
        JsonArray oldFormula = new JsonArray();
        for (int i = 0; i < 200; i++) {
            double t = i < 100 ? i : randDouble();
            oldFormula.add(row(d(t), d(ActionCosts.oldFormula(t))));
        }
        o.add("old_formula", oldFormula);

        // [distance, distanceToTicks]
        JsonArray distanceToTicks = new JsonArray();
        double[] fixed = {0.0, -0.0, -1.0, 0.25, 1.25, 0.5, 1e-12, 4096.5, 100000.0, Double.MIN_VALUE};
        for (double v : fixed) {
            distanceToTicks.add(row(d(v), d(ActionCosts.distanceToTicks(v))));
        }
        for (int i = 0; i < 300; i++) {
            double v = R.nextDouble() * (i < 200 ? 64 : 10000);
            distanceToTicks.add(row(d(v), d(ActionCosts.distanceToTicks(v))));
        }
        o.add("distance_to_ticks", distanceToTicks);
        return o;
    }

    private static JsonObject baritoneMath() {
        JsonObject o = new JsonObject();
        // [in, fastFloor, fastCeil]
        JsonArray rows = new JsonArray();
        for (int i = 0; i < 400; i++) {
            double v = i < 200 ? (R.nextDouble() - 0.5) * 2e4 : randDouble();
            rows.add(row(d(v), BaritoneMath.fastFloor(v), BaritoneMath.fastCeil(v)));
        }
        o.add("fast_floor_ceil", rows);
        return o;
    }

    private static JsonObject rotation() {
        JsonObject o = new JsonObject();

        // [in, normalizeYaw, clampPitch]
        JsonArray single = new JsonArray();
        for (int i = 0; i < 300; i++) {
            float v = randAngle();
            single.add(row(f(v), f(Rotation.normalizeYaw(v)), f(Rotation.clampPitch(v))));
        }
        o.add("normalize_clamp", single);

        // [yaw, offsetYaw, yawDistanceFromOffset]
        JsonArray yawDistance = new JsonArray();
        for (int i = 0; i < 300; i++) {
            float a = randAngle(), b = randAngle();
            yawDistance.add(row(f(a), f(b), f(Rotation.yawDistanceFromOffset(a, b))));
        }
        o.add("yaw_distance_from_offset", yawDistance);

        // [ay, ap, by, bp, add.yaw, add.pitch, subtract.yaw, subtract.pitch,
        //  normalizeAndClamp(a).yaw, normalizeAndClamp(a).pitch, isReallyCloseTo, yawIsReallyClose]
        JsonArray pairs = new JsonArray();
        for (int i = 0; i < 400; i++) {
            Rotation a = new Rotation(randAngle(), randAngle());
            Rotation b;
            switch (i % 4) {
                case 0 -> b = new Rotation(a.getYaw() + (R.nextFloat() - 0.5F) * 0.03F, a.getPitch() + (R.nextFloat() - 0.5F) * 0.03F);
                case 1 -> b = new Rotation(a.getYaw() + 360F * (R.nextInt(5) - 2) + (R.nextFloat() - 0.5F) * 0.03F, a.getPitch());
                default -> b = new Rotation(randAngle(), randAngle());
            }
            Rotation add = a.add(b);
            Rotation sub = a.subtract(b);
            Rotation nc = a.normalizeAndClamp();
            pairs.add(row(f(a.getYaw()), f(a.getPitch()), f(b.getYaw()), f(b.getPitch()),
                    f(add.getYaw()), f(add.getPitch()), f(sub.getYaw()), f(sub.getPitch()),
                    f(nc.getYaw()), f(nc.getPitch()), a.isReallyCloseTo(b), a.yawIsReallyClose(b)));
        }
        o.add("pairs", pairs);
        return o;
    }

    // region RotationUtils: pure methods copied verbatim from upstream RotationUtils (it cannot be
    // compiled standalone, it depends on IPlayerContext / LookBehavior)

    private static final double RAD_TO_DEG = 180.0 / Math.PI;
    private static final float DEG_TO_RAD_F = (float) (Math.PI / 180.0);

    private static Rotation calcRotationFromCoords(BlockPos orig, BlockPos dest) {
        return calcRotationFromVec3d(new Vec3(orig.getX(), orig.getY(), orig.getZ()), new Vec3(dest.getX(), dest.getY(), dest.getZ()));
    }

    private static Rotation wrapAnglesToRelative(Rotation current, Rotation target) {
        if (current.yawIsReallyClose(target)) {
            return new Rotation(current.getYaw(), target.getPitch());
        }
        return target.subtract(current).normalize().add(current);
    }

    private static Rotation calcRotationFromVec3d(Vec3 orig, Vec3 dest, Rotation current) {
        return wrapAnglesToRelative(current, calcRotationFromVec3d(orig, dest));
    }

    private static Rotation calcRotationFromVec3d(Vec3 orig, Vec3 dest) {
        double[] delta = {orig.x - dest.x, orig.y - dest.y, orig.z - dest.z};
        double yaw = Mth.atan2(delta[0], -delta[2]);
        double dist = Math.sqrt(delta[0] * delta[0] + delta[2] * delta[2]);
        double pitch = Mth.atan2(delta[1], dist);
        return new Rotation(
                (float) (yaw * RAD_TO_DEG),
                (float) (pitch * RAD_TO_DEG)
        );
    }

    private static Vec3 calcLookDirectionFromRotation(Rotation rotation) {
        float flatZ = Mth.cos((-rotation.getYaw() * DEG_TO_RAD_F) - (float) Math.PI);
        float flatX = Mth.sin((-rotation.getYaw() * DEG_TO_RAD_F) - (float) Math.PI);
        float pitchBase = -Mth.cos(-rotation.getPitch() * DEG_TO_RAD_F);
        float pitchHeight = Mth.sin(-rotation.getPitch() * DEG_TO_RAD_F);
        return new Vec3(flatX * pitchBase, pitchHeight, flatZ * pitchBase);
    }

    // endregion

    private static Vec3 randVec() {
        return switch (R.nextInt(3)) {
            case 0 -> new Vec3(R.nextInt(64) - 32 + 0.5, R.nextInt(64) - 32 + 0.5, R.nextInt(64) - 32 + 0.5);
            case 1 -> new Vec3((R.nextDouble() - 0.5) * 20, (R.nextDouble() - 0.5) * 20, (R.nextDouble() - 0.5) * 20);
            default -> new Vec3((R.nextDouble() - 0.5) * 2e5, (R.nextDouble() - 0.5) * 600, (R.nextDouble() - 0.5) * 2e5);
        };
    }

    private static JsonObject rotationUtils() {
        JsonObject o = new JsonObject();

        // [orig xyz, dest xyz, current yaw, current pitch, plain yaw, plain pitch, relative yaw, relative pitch]
        JsonArray fromVec = new JsonArray();
        for (int i = 0; i < 400; i++) {
            Vec3 a = randVec();
            Vec3 b = i % 10 == 0 ? a : randVec();
            Rotation current = new Rotation(randAngle(), randAngle());
            Rotation plain = calcRotationFromVec3d(a, b);
            if (i % 5 == 0) {
                current = new Rotation(plain.getYaw() + 360F * (R.nextInt(5) - 2) + (R.nextFloat() - 0.5F) * 0.03F, randAngle());
            }
            Rotation rel = calcRotationFromVec3d(a, b, current);
            fromVec.add(row(d(a.x), d(a.y), d(a.z), d(b.x), d(b.y), d(b.z), f(current.getYaw()), f(current.getPitch()),
                    f(plain.getYaw()), f(plain.getPitch()), f(rel.getYaw()), f(rel.getPitch())));
        }
        o.add("calc_rotation_from_vec3d", fromVec);

        // [orig xyz, dest xyz, yaw, pitch]
        JsonArray fromCoords = new JsonArray();
        for (int i = 0; i < 200; i++) {
            BlockPos a = new BlockPos(R.nextInt(2000) - 1000, R.nextInt(400) - 64, R.nextInt(2000) - 1000);
            BlockPos b = i % 3 == 0 ? a.offset(R.nextInt(9) - 4, R.nextInt(9) - 4, R.nextInt(9) - 4) : new BlockPos(randInt(), randInt(), randInt());
            Rotation r = calcRotationFromCoords(a, b);
            fromCoords.add(row(a.getX(), a.getY(), a.getZ(), b.getX(), b.getY(), b.getZ(), f(r.getYaw()), f(r.getPitch())));
        }
        o.add("calc_rotation_from_coords", fromCoords);

        // [yaw, pitch, x, y, z]
        JsonArray look = new JsonArray();
        for (int i = 0; i < 400; i++) {
            Rotation r = new Rotation(randAngle(), randAngle());
            Vec3 v = calcLookDirectionFromRotation(r);
            look.add(row(f(r.getYaw()), f(r.getPitch()), d(v.x), d(v.y), d(v.z)));
        }
        o.add("calc_look_direction_from_rotation", look);
        return o;
    }

    // region goals

    private static JsonObject spec(String kind, Object... kv) {
        JsonObject o = new JsonObject();
        o.addProperty("kind", kind);
        for (int i = 0; i < kv.length; i += 2) {
            Object v = kv[i + 1];
            o.add((String) kv[i], v instanceof JsonElement e ? e : v == null ? JsonNull.INSTANCE : row(v).get(0));
        }
        return o;
    }

    private record GoalCase(JsonObject spec, Goal goal, BlockPos anchor) {}

    private static GoalCase block(int x, int y, int z) {
        return new GoalCase(spec("GoalBlock", "x", x, "y", y, "z", z), new GoalBlock(x, y, z), new BlockPos(x, y, z));
    }

    private static GoalCase xz(int x, int z) {
        return new GoalCase(spec("GoalXZ", "x", x, "z", z), new GoalXZ(x, z), new BlockPos(x, 64, z));
    }

    private static GoalCase yLevel(int level) {
        return new GoalCase(spec("GoalYLevel", "level", level), new GoalYLevel(level), new BlockPos(0, level, 0));
    }

    private static GoalCase runAway(double distance, Integer maintainY, BlockPos... from) {
        JsonArray fromJson = new JsonArray();
        BetterBlockPos[] better = new BetterBlockPos[from.length];
        for (int i = 0; i < from.length; i++) {
            fromJson.add(pos(from[i]));
            better[i] = new BetterBlockPos(from[i]);
        }
        return new GoalCase(spec("GoalRunAway", "distance", d(distance), "maintain_y", maintainY, "from", fromJson),
                new GoalRunAway(distance, maintainY, better), from[0]);
    }

    private static GoalCase composite(GoalCase... cases) {
        JsonArray specs = new JsonArray();
        Goal[] goals = new Goal[cases.length];
        for (int i = 0; i < cases.length; i++) {
            specs.add(cases[i].spec);
            goals[i] = cases[i].goal;
        }
        return new GoalCase(spec("GoalComposite", "goals", specs), new GoalComposite(goals),
                cases.length == 0 ? BlockPos.ZERO : cases[0].anchor);
    }

    private static GoalCase inverted(GoalCase origin) {
        return new GoalCase(spec("GoalInverted", "origin", origin.spec), new GoalInverted(origin.goal), origin.anchor);
    }

    private static JsonArray goals() {
        List<GoalCase> cases = new ArrayList<>();
        cases.add(block(10, 64, -20));
        cases.add(block(2147483000, -2147483000, 5));
        cases.add(new GoalCase(spec("GoalTwoBlocks", "x", 0, "y", 70, "z", 0), new GoalTwoBlocks(0, 70, 0), new BlockPos(0, 70, 0)));
        cases.add(new GoalCase(spec("GoalGetToBlock", "x", -5, "y", 12, "z", 7), new GoalGetToBlock(new BlockPos(-5, 12, 7)), new BlockPos(-5, 12, 7)));
        for (int[] n : new int[][]{{100, 64, 100, 3}, {0, 0, 0, 0}, {-7, 5, 3, 1}, {1, 2, 3, 6}}) {
            BlockPos p = new BlockPos(n[0], n[1], n[2]);
            cases.add(new GoalCase(spec("GoalNear", "x", n[0], "y", n[1], "z", n[2], "range", n[3]), new GoalNear(p, n[3]), p));
        }
        cases.add(xz(123, -456));
        cases.add(xz(Integer.MAX_VALUE, Integer.MIN_VALUE));
        cases.add(yLevel(64));
        cases.add(yLevel(-59));
        cases.add(new GoalCase(spec("GoalAxis"), new GoalAxis(), new BlockPos(0, 120, 0)));
        for (Direction dir : new Direction[]{Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST}) {
            BlockPos p = new BlockPos(10, 64, -10);
            cases.add(new GoalCase(spec("GoalStrictDirection", "x", p.getX(), "y", p.getY(), "z", p.getZ(), "direction", dir.getName()),
                    new GoalStrictDirection(p, dir), p));
        }
        cases.add(runAway(5.5, null, new BlockPos(0, 64, 0)));
        cases.add(runAway(3, 70, new BlockPos(10, 64, 10), new BlockPos(-10, 64, -10)));
        cases.add(runAway(4, null, new BlockPos(-3, 64, 2), new BlockPos(5, 60, 5)));
        cases.add(composite(block(1, 2, 3), xz(100, 100), yLevel(12)));
        cases.add(composite());
        cases.add(inverted(block(0, 64, 0)));
        cases.add(inverted(composite(block(5, 5, 5), yLevel(-10))));

        JsonArray out = new JsonArray();
        for (GoalCase c : cases) {
            JsonObject o = new JsonObject();
            o.add("spec", c.spec);
            o.addProperty("to_string", c.goal.toString());
            o.add("heuristic_at_goal", d(c.goal.heuristic()));
            // [x, y, z, isInGoal, heuristic]
            JsonArray samples = new JsonArray();
            for (int i = 0; i < 250; i++) {
                int x, y, z;
                if (i < 125) {
                    x = c.anchor.getX() + R.nextInt(13) - 6;
                    y = c.anchor.getY() + R.nextInt(13) - 6;
                    z = c.anchor.getZ() + R.nextInt(13) - 6;
                } else if (i < 200) {
                    x = R.nextInt(4000) - 2000;
                    y = R.nextInt(384) - 64;
                    z = R.nextInt(4000) - 2000;
                } else {
                    x = randInt();
                    y = randInt();
                    z = randInt();
                }
                samples.add(row(x, y, z, c.goal.isInGoal(x, y, z), d(c.goal.heuristic(x, y, z))));
            }
            o.add("samples", samples);
            out.add(o);
        }
        return out;
    }

    private static JsonObject goalStatics() {
        JsonObject o = new JsonObject();

        // [xDiff, yDiff, zDiff, GoalBlock.calculate]
        JsonArray block = new JsonArray();
        for (int i = 0; i < 200; i++) {
            double x = i < 100 ? R.nextInt(200) - 100 : randFiniteDouble();
            double z = i < 100 ? R.nextInt(200) - 100 : randFiniteDouble();
            int y = i < 100 ? R.nextInt(200) - 100 : randInt();
            block.add(row(d(x), y, d(z), d(GoalBlock.calculate(x, y, z))));
        }
        o.add("goal_block_calculate", block);

        // [xDiff, zDiff, GoalXZ.calculate]
        JsonArray xz = new JsonArray();
        for (int i = 0; i < 200; i++) {
            double x = i < 100 ? R.nextInt(200) - 100 : randDouble();
            double z = i < 100 ? R.nextInt(200) - 100 : randDouble();
            xz.add(row(d(x), d(z), d(GoalXZ.calculate(x, z))));
        }
        o.add("goal_xz_calculate", xz);

        // [goalY, currentY, GoalYLevel.calculate]
        JsonArray yLevel = new JsonArray();
        for (int i = 0; i < 200; i++) {
            int g = i < 100 ? R.nextInt(400) - 64 : randInt();
            int c = i < 100 ? R.nextInt(400) - 64 : randInt();
            yLevel.add(row(g, c, d(GoalYLevel.calculate(g, c))));
        }
        o.add("goal_y_level_calculate", yLevel);

        // [origin xyz, yaw, distance, goal x, goal z]
        JsonArray fromDirection = new JsonArray();
        for (int i = 0; i < 300; i++) {
            Vec3 origin = randVec();
            float yaw = randAngle();
            double distance = i < 200 ? R.nextDouble() * 1000 : randFiniteDouble();
            GoalXZ g = GoalXZ.fromDirection(origin, yaw, distance);
            fromDirection.add(row(d(origin.x), d(origin.y), d(origin.z), f(yaw), d(distance), g.getX(), g.getZ()));
        }
        o.add("goal_xz_from_direction", fromDirection);
        return o;
    }

    // endregion
}
